### ISSUE TITLE
Problem: Debouncing through step(blockMS) with blockMs = numerical_limits<size_t>::max doesnt work

### ISSUE THREAD

**Issue by gabm** [tklab-tud/uscxml#101]
Debouncing `step` with the default value of `step(std::numerical_limits<size_t>::max())` doesn't work.

The reason is because `size_t` is an `unsigned long` while the representation of std::chrono::milliseconds is `int64` on my system. So we basically get an overflow while calculating the `endTime` which probably lies in the past. This corrupted value of `unsigned long` is then used straight away in BasicEventQueue.cpp`: 

```
auto endTime = std::chrono::system_clock::now() + std::chrono::milliseconds(blockMs);
while (endTime > std::chrono::system_clock::now() && _queue.empty()) {
    _cond.wait_until(_mutex, endTime);
}
```

Possible Solutions:
- define a sane max value (1e6 msec or more). That would work in any case..
- make the max value dependent on the representation of std::chrono::system_clock (that would introduce chrono dependency)
- use std::chrono::system_clock::duration::max() right away as default value

I'd go with the last option, what do you think @sradomski ?

**Comment by sradomski** [comment]
I'd very much like to avoid any dependency on `<chrono>` in `Interpreter.h` as the file is subjected to SWIG for the language bindings and I'd like to keep them as conservative as possible. What about checking blockMs in dequeue and limiting endTime to `std::chrono::system_clock::time_point::max()`, would that work?

    if (blockMs > 0) {
        using namespace std::chrono;

        system_clock::time_point now = system_clock::now();
        system_clock::time_point endTime = now + milliseconds(blockMs);

        // now + milliseconds(blockMs) may not have fitted into a duration type - limit to maximum duration
        if (blockMs > system_clock::duration::max().count() - duration_cast<milliseconds>(now.time_since_epoch()).count()) {
            endTime = system_clock::time_point::max();
        }
        
        // block for given milliseconds or until queue is non-empty
        while (endTime > std::chrono::system_clock::now() && _queue.empty()) {
            _cond.wait_until(_mutex, endTime);
        }
    }

**Comment by sradomski** [comment]
And thank you for catching it!

**Comment by gabm** [comment]
guess that should work. Maybe it would be easier to read/understand like this: 


```
if (blockMs > 0) {
    using namespace std::chrono;

    system_clock::time_point endTime;
    if (blockMs <= std::numerical_limits<system_clock::duration::rep>::max()
         endTime =  system_clock::now() + milliseconds(blockMs);
    else
         endTime = system_clock::now() + system_clock::duration::max()
    
    // block for given milliseconds or until queue is non-empty
    while (endTime > std::chrono::system_clock::now() && _queue.empty()) {
        _cond.wait_until(_mutex, endTime);
    }
}

```

**Comment by sradomski** [comment]
But your code would only check if `blockMs` can still be represented, not if `blockMs + now` can be as well. For values of `blockMs` that are just shy of the maximum value, the addition of `now` would trigger an overflow, wouldn't it?

**Comment by gabm** [comment]
:smile: yes... you're right! want a MR?

**Comment by sradomski** [comment]
It's already committed, but thank you!
