### ISSUE TITLE
binding support for the Python

### ISSUE THREAD

**Issue by edbek** [tklab-tud/uscxml#103]
Dear Stefan, whether you can do for SCXML interpreter also binding support for the Python language ?

**Comment by sradomski** [comment]
[Merry Christmas](https://github.com/tklab-tud/uscxml/commit/cbb57aadbfe11269297c36f578d4a440a3602436) - it's a first approach. If the Python headers are libraries are found, it will generate a native Python uscxml module and a corresponding Python wrapper in the library folder:

    $ ls lib |grep Python
    _uscxmlNativePython.so
    uscxmlNativePython.py

Let me know how it works for you.
