### ISSUE TITLE
whether is uscxml reetrantnym code?

### ISSUE THREAD

**Issue by edbek** [tklab-tud/uscxml#104]
whether is uscxml reetrantnym code? I can run at the same time a lot of interpreters uscxml, each with its own file interpretetor * .scxml?

**Comment by sradomski** [comment]
Well, most of uscxml is reentrant as there is hardly any shared state among interpreters. you can, however, not call step() on the same interpreter concurrently from different threads. Enqueuing events, however, is reentrant again. When in doubt have a look whether I aqcuire a scoped lock at the beginning of the function. 

It is no problem at all to have as many interpreter objects as memory allows. At the very least I'd consider anything else a bug and fix it. 
  Stefan
