### ISSUE TITLE
why replaced Arabica DOM implementation with Xerces-C

### ISSUE THREAD

**Issue by su6838354** [tklab-tud/uscxml#108]
https://github.com/tklab-tud/uscxml/commit/b62e7979600feee23dc7cdb61042a8fc7673122b
I find you replaced Arabica DOM implementation with Xerces-C，this is a giant work. I am curious why you did it？At the beginning the perfermance of this interpreter was affected by the arabica mybe the dynamic_cast the pointer of dom. Now the Xerces-C is efficient in perfermace?

**Comment by sradomski** [comment]
Tons of dynamic_cast and the removal of DOMEvents I submitted some years ago were the prime reasons iirc.
