### ISSUE TITLE
[Lua datamodel] Unpredictable behaviour in <assign> element using variables in location

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#109]
Hello, I'm trying to use variables in location during assigning the data 
`<assign expr="1" location="VarArray[Var1]"/>`
and I neither get the data changed nor any errors from interpreter. 

So, can we use variables in location?
If not why we don't have any warnings or errors?
P.S. If I use <script> element for assigning the data, everything works fine.

```
<scxml datamodel="lua" initial="StateShape1" name="ScxmlShape1" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<datamodel>
		<data id="VarArray">{ 0, 0, 0 }</data>
		<data expr="1" id="Var1"/>
	</datamodel>
	<state id="StateShape1">
		<onentry>
			<assign expr="555" location="VarArray[Var1]"/>
		</onentry>
		<transition cond="VarArray[1]~=0" target="Pass"/>
		<transition event="error.*" target="Fail"/>
		<transition cond="VarArray[1]==0" target="Unknown"/>
	</state>
	<final id="Pass"/>
	<final id="Fail"/>
	<final id="Unknown"/>
</scxml>
```

**Comment by sradomski** [comment]
Yes, the respective piece of code from my side is nothing to be proud about. I do create LuaRefs for anything that you pass as data but I cannot get a LuaRef for the location by merely evaluating the expression. Instead, I have to parse the string and descent the tables starting from the topmost global. However, it's fixed now.
