### ISSUE TITLE
[Lua datamodel] Access violation during parallel work of invoked sessions with the same source

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#111]
Hello, first of all scxml code.

[sample1.scxml](https://github.com/tklab-tud/uscxml/files/958349/sample1.txt)
[sub1.scxml](https://github.com/tklab-tud/uscxml/files/958351/sub1.txt)
[main.cpp](https://github.com/tklab-tud/uscxml/files/958366/main.txt)

During execution of this code I'm getting sometimes different exceptions. Sometimes 
> Access violation reading location

in different places of **LuaRef** class
![Assign value to table key](https://cloud.githubusercontent.com/assets/18611095/25435705/9c0ad374-2a99-11e7-9d46-8517852576e2.png)

or sometimes in **LuaDataModel** class
![luaEval](https://cloud.githubusercontent.com/assets/18611095/25435796/f4c9644e-2a99-11e7-808e-a4f7de9e33ae.png)

and sometimes it may work without errors

**Comment by sradomski** [comment]
I assume this was cause by me not instantiating a new datamodel upon invocation of another SCXML state-chart. Can you please check whether this is still the case?

**Comment by sradomski** [comment]
And thank you very much for reporting these bugs!

**Comment by alexzhornyak** [comment]
Thank you very much for so quick fixes. Now everything works fine! :+1:
