### ISSUE TITLE
[Lua datamodel] Access violation when LOM is not assigned

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#112]
Hello, if LOM is not assigned (lxp.dll is missing) I'm getting 'Access violation' during logging in LuaDataModel class.

![2017-04-26 16 35 19](https://cloud.githubusercontent.com/assets/18611095/25437726/ffb3d884-2a9f-11e7-9f2a-9d0907bd1fa6.png)

**Comment by sradomski** [comment]
good catch - that ought to be dm→_callbacks or callbacks as the first argument to the LOG macro, _callbacks is not initialized. I will fix once I had a look at the other issues.
