### ISSUE TITLE
Unconvinient processing of <log> element

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#113]
Hello, in current implementation of uscxml, processing of \<log\> element generates in output 4 strings instead of expectable 1.

> Log: 
> Log: Outcome: 
> Log: 
> Log: pass

If we are debugging difficult project, especially with invokings, strings can be so mixed, that we can not understand which log is it.
So, my offer to transform a little bit **processLog** function

```
void BasicContentExecutor::processLog(XERCESC_NS::DOMElement* content) {
	std::string label = ATTR(content, kXMLCharLabel);
	std::string expr = ATTR(content, kXMLCharExpr);

	Data d = _callbacks->evalAsData(expr);
	/*if (label.size() > 0) {
		_callbacks->getLogger().log(USCXML_LOG) << label << ": ";
	}
	_callbacks->getLogger().log(USCXML_LOG) << d << std::endl;*/

        // let's make one line log :)
	_callbacks->getLogger().log(USCXML_LOG) << (label.size() > 0 ? label + ":" : "") << d << std::endl;
}
```

**Comment by sradomski** [comment]
The issue is the StdOutLogger insisting on adding std::endl to every invocation, I dropped this part and kept processLog as it is.

**Comment by alexzhornyak** [comment]
I checked how it works now and I am not satisfied because in log string now I see 4 times the word **log**
For example:
> Log: Log: Impulse:: Log: Log: 7994ce49-3c64-461e-b6c9-bc8d98f2c314

I would like to see something like this
> Log: Impulse:7994ce49-3c64-461e-b6c9-bc8d98f2c314

**Comment by sradomski** [comment]
Yes, sorry .. been late yesterday - ought to be better now

**Comment by alexzhornyak** [comment]
Severity words are still duplicated

> [Info] [Info] Registering at unstarted HTTP Server

> [Log] [Log] Outcome:"pass"

**Comment by sradomski** [comment]
I am afraid I cannot reproduce - are you seeing these with the w3c test scxml documents as well?

**Comment by alexzhornyak** [comment]
With version of usxml dated on 27.04.2017 I see next:
![2017-04-28 09 15 24](https://cloud.githubusercontent.com/assets/18611095/25516621/4cee37d4-2bf4-11e7-8377-849f7f37a35b.png)

**Comment by sradomski** [comment]
Could you please see if this is indeed still the case? I cannot reproduce.

    C:\Users\sradomski\uscxml\bin>uscxml-browser.exe Y:\uscxml\test\w3c\null\test436.scxml
    [Info] HTTP server listening on tcp/5080
    [Info] WebSocket server listening on tcp/5081
    [Info] Processing Y:\uscxml\test\w3c\null\test436.scxml
    [Log] Outcome: "'pass'"

**Comment by alexzhornyak** [comment]
![2017-05-03 09 30 54](https://cloud.githubusercontent.com/assets/18611095/25650112/4cca385a-2fe3-11e7-8ca9-fdd0d75a3e26.png)

I don't know, may this is Windows behaviour. Ok, leave it as is. This is not a big problem

**Comment by sradomski** [comment]
Did you rebuild? I am testing on windows myself and do not see the double log marks.

**Comment by alexzhornyak** [comment]
I've tested on commit "Fixed issue113 for real" on Apr 27, 2017

**Comment by alexzhornyak** [comment]
Ok, I've downloaded latesst - "Optimized ANSI-C transformation" on Apr 30, 2017
And debugged uscxml-browser.exe and understood what's happened:

This part `_callbacks->getLogger().log(USCXML_LOG)` calls destructor of StreamLogger

![2017-05-03 11 57 00](https://cloud.githubusercontent.com/assets/18611095/25654011/1dc1d51c-2ff8-11e7-8489-5f5c09caa359.png)

![2017-05-03 11 55 04](https://cloud.githubusercontent.com/assets/18611095/25654018/27fecd3c-2ff8-11e7-8672-f33b875f2d80.png)

**Comment by sradomski** [comment]
Ok, I did install Visual Studio 2013 and can, indeed, reproduce the issue. I will give it a look once I have some more time.

**Comment by sradomski** [comment]
It was an issue with the compiler calling the copy constructor and destructor for the StreamLogger instance being returned from log(severity) already. And indeed it is compiler specific, I guess that newer compilers generate a move constructor and do not invoke the destructor twice. Solved with latest push.
