### ISSUE TITLE
error: Interpreter has no XML document

### ISSUE THREAD

**Issue by edbek** [tklab-tud/uscxml#115]
At startup

```
> # transform given SCXML document into ANSI-C fragment
> $ uscxml-transform -tc -i https://raw.githubusercontent.com/tklab-tud/uscxml/master/test/w3c/null/test436.scxml
```

The output is:

```
Info: 
Info: HTTP server listening on tcp/30444
Info: 
Info: WebSocket server listening on tcp/30445
Error: 
Error: unable to open primary document entity 'file:///C:/uscxml/bin/test200.scxml'
  Internal Event 
    name: error.platform
    data: 
  {
    "cause": "Interpreter has no XML document", 
    "file":  "C:\\uscxml\\src\\uscxml\\interpreter\\InterpreterImpl.cpp", 
    "line":  262
  }


```
what is the reason ?
Assembly carried out on Wimdows 8.1

**Comment by sradomski** [comment]
Guss it's URL handling on windows, I'll look into it.

**Comment by sradomski** [comment]
Oh, I remember: When we build curl on windows at configure time, we do not build with OpenSSL support because it is plainly ridiculous to setup from within the build system automatically. You will have to provide your own curl binary and header files and place it somewhere where [FindCurl.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindCURL.cmake) will pick it up.

Alternatively, you can download the file and refer to it via a local file:/// url. Nevertheless, I will see to it that the reason is more clearly communicated. I will leave this open in case that there is another issue with the approach.

**Comment by sradomski** [comment]
It is working if you provide the document as a simple path as opposed to a URL:

    $ bin\uscxml-transform.exe -tc -i c:\uscxml\test\w3c\null\test436.scxml

I'll have a look what's wrong with file urls on windows at the weekend.

**Comment by sradomski** [comment]
P.S.: I just recently used the ANSI-C transformation to model the control logic for an ATMega328 and will prepare a small case study / tutorial once I polished it.

**Comment by edbek** [comment]
The result is the same:

`> uscxml-transform.exe -tc -i test436.scxml
`

```
Info: 
Info: HTTP server listening on tcp/30444
Info: 
Info: WebSocket server listening on tcp/30445
Error: 
Error: unable to open primary document entity 'file:///C:/uscxml/bin/test436.scxml'
  Internal Event 
    name: error.platform
    data: 
  {
    "cause": "Interpreter has no XML document", 
    "file":  "C:\\uscxml\\src\\uscxml\\interpreter\\InterpreterImpl.cpp", 
    "line":  262
  }


```

**Comment by sradomski** [comment]
This is working here on Windows 10:

    $ bin\uscxml-transform.exe -tc -i file:///c:/uscxml/test/w3c/null/test436.scxml

It's windows' brain dead [file URL convention](https://en.wikipedia.org/wiki/File_URI_scheme#Windows_2). Though, one would very much expect that a file path as in your examples ought to work and indeed it does on unices. I'll work on it during the weekend.

**Comment by edbek** [comment]
It is possible that I have errors in the assembly of the full project, because, for example, the file "test-gen-c.exe" does not start (Windows stops the program with an error).

**Comment by sradomski** [comment]
Yes, same here .. it's been in preparation for a master thesis with Contiki and is not polished. Nevertheless, it should not abort like this. We do have the windows build slaves but other than that I am somewhat focussed on unices, will look into it.

**Comment by edbek** [comment]
Yes, when a full local path "file:///c:/uscxml/test/w3c/null/test436.scxml" is given, then it works !

**Comment by sradomski** [comment]
I did some more optimizations to reduce the code size for embedded devices:

- history handling optional
- event delay as a long instead of a char array
- support for "native" datamodel inserted verbatim

I will push them somewhen during the next week once I am confident that they do not break too many things :)

**Comment by edbek** [comment]
Whether can the program "uscxml-tranform.exe" in the future to transform scxml-code in the Lua-code?

**Comment by sradomski** [comment]
You want to transpile onto Lua? I am afraid that my Lua is maybe not up to the task, one possible way is to provide a transpilation target "[haxe](https://haxe.org)" and use their transpilers for specific languages.

**Comment by edbek** [comment]
As I understand it, will you make transformation the scxml-code into the Haxe-code ? If so, when can this be expected?

**Comment by sradomski** [comment]
Not sure when this will be ready. I do have an intimate familiarity with SCXML's microstep algorithm and would only generate that in Haxe. I.e. you would still be responsible to actually *do* things, I'd just trigger callbacks in the right order, much like the current ANSI-C transpilation. However, I have never worked with Haxe and will have to read up on it. I do have some time tomorrow, but there is also a backlog of issues.

**Comment by edbek** [comment]
Tell me, please, how to work further with the "test436.c" file received through the program "uscxml-transform.exe"?

**Comment by sradomski** [comment]
You include it into another compilation unit, instantiate a uscxml_ctx, register callbacks and pass it to uscxml_step to perform a microstep:

    uscxml_ctx ctx;
    memset(&ctx, 0, sizeof(uscxml_ctx));
    ctx.machine = &USCXML_MACHINE;
    ctx.invoke = invoke;
    ctx.is_matched = matched;
    ctx.dequeue_external = dequeueExternal;
    ctx.exec_content_send = send;
    while((err = uscxml_step(&ctx)) != USCXML_ERR_IDLE) {}

This will run the state chart until you return NULL from the dequeueExternal function. You only need to register callbacks for the functionality you plan to use. I will prepare a small example with my ATMega328 this evening.

**Comment by sradomski** [comment]
I do provide a more meaningful message when I cannot parse the URL now, I also accept non-url simple file path. If you provide a file URL, I do insist on a proper Windows file URL though.

**Comment by edbek** [comment]
Dear Stefan, yes everything works. I've ported the files received via  "uscxml-transform.exe"  *.scxml to c-files on STM32Fxxx processors. Everything works well.

But there was one more question for the future: at present we have the opportunity to receive c-files from *.scxml files. And whether it is possible to make, that from *.scxml files (as well as the program "uscxml-transform.exe") we also received text representation of the necessary business task (technical task). Then there will be a complete set between the client and the developer: the customer will have a technical task, and the developer will have C-files.

**Comment by sradomski** [comment]
I am not sure how I would arrive at a "text representation of the necessary business task" from the SCXML file? What is a representation of a business task and how would I generate one from the SCXML file? If you could elaborate on this and post it as another issue with an `enhancement` label, I will consider it.
