### ISSUE TITLE
Some functions require to be exported if use uscxml as dynamic library

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#117]
Hello, I'm compiling uscxml-browser with uscxml linked as dynamic library and I see unresolved externals 'usxml::iequals' and 'uscxml::StreamLogger', so I changed the signature to solve this:

Convinience.h
`bool USCXML_API iequals(const std::string& a, const std::string& b);`

Logging.h
`class USCXML_API StreamLogger`

If I did wrong, please, tell me how to do it in correct way

**Comment by sradomski** [comment]
Fixed with latest push. This will creep up ever again as we build as a static library on windows per default and the whole `__declspec()` issue is only relevant for dlls. In the best of all worlds, we would have our windows build slaves build both versions. Closing for now.
