### ISSUE TITLE
W3c test216.scxml failing for Promela Datamodel.

### ISSUE THREAD

**Issue by parora1701** [tklab-tud/uscxml#123]
This test invokes another scxml using variable var1.  On first glance It seems variable expression is not evaluated correctly and it still maintains prefix "file: at invoker call.
![issue](https://cloud.githubusercontent.com/assets/5223842/25847631/3045c52c-34b7-11e7-9231-5af17b374338.JPG)

**Comment by sradomski** [comment]
I am not sure whether I'd like to support this one in the Promela datamodel. It is not expressible in PROMELA anyway due to dynamic loading of external code and can easily be transformed into an invoke with a dedicated `src` attribute. Is this one actually important for your work?

**Comment by parora1701** [comment]
While not critical still I will have to argue about failed test cases in my report. But I guess this is enough i will refer to PROMELA datamodel results in uscxml for the failed ones.

**Comment by sradomski** [comment]
In fact, it does pass here under MacOS and Windows - please make sure that you have the most recent version installed.
