### ISSUE TITLE
[Lua datamodel] Test 179 is not passed

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#124]
Hello, we can not pass test 179 with LuaDataModel, because in this test we are sending event with content that is number value equal to 123, then we converting it to string because of the code in function **BasicContentExecutor::elementAsData**
```
if (LOCALNAME(element) == "content") {
	return Data(spaceNormalize(contentSS.str()), Data::VERBATIM);
```
And of course we can't pass the condition
`_event.data==123` because _event.data is string and equal "123", so `"123"~=123`
that's why first of all we need to check wether content is a valid data value
```
// need first try getAsData because how to pass 179 ?
 try {
	// test153, we need to throw for test150 in promela
	Data d = _callbacks->getAsData(contentSS.str());
	if (!d.empty())
	        return d;
}
catch (ErrorEvent &) {
	// test294, test562       
       return Data(spaceNormalize(contentSS.str()), Data::VERBATIM);
}
```

**Comment by sradomski** [comment]
On MacOS I got:

    $ ctest -L w3c/lua/test179.scxml
    Test project /Users/sradomski/Documents/TK/Code/uscxml/build/cli
        Start 438: w3c/lua/test179.scxml
    1/1 Test #438: w3c/lua/test179.scxml ............   Passed    0.08 sec
    
    100% tests passed, 0 tests failed out of 1
    
    Label Time Summary:
    w3c/lua/test179.scxml    =   0.08 sec (1 test)
    
    Total Test time (real) =   0.26 sec

**Comment by sradomski** [comment]
On Windows 7 with Visual Studio 12 on 32 Bit I got:

    >ctest -L w3c/lua/test179.scxml
    Test project C:/Users/sradomski/Desktop/build/uscxml/vs14-32-nmake
        Start 436: w3c/lua/test179.scxml
    1/1 Test #436: w3c/lua/test179.scxml ............   Passed    0.61 sec
    
    100% tests passed, 0 tests failed out of 1
    
    Label Time Summary:
    w3c/lua/test179.scxml    =   0.61 sec (1 test)
    
    Total Test time (real) =   0.78 sec

What compiler / platform are you using?

**Comment by alexzhornyak** [comment]
I really can not understand how could you pass it in every platform because I do see where the problem is.
1) my position in git
![2017-05-10 23 51 44](https://cloud.githubusercontent.com/assets/18611095/25921288/909db354-35dd-11e7-9c59-bed56f1f75b5.png)
2) Visual Studio 2013 Ultimate 32 Bit, Win 7 SP 1

And now debugging step by step (I'm passing 'test179.scxml' to uscxml-browser.exe)

![2017-05-11 00 10 13](https://cloud.githubusercontent.com/assets/18611095/25921804/8497d858-35df-11e7-907e-527d2bc5fc59.png)
![2017-05-11 00 12 45](https://cloud.githubusercontent.com/assets/18611095/25921813/8d8cf2ea-35df-11e7-9c0d-645bad0281ce.png)
![2017-05-10 23 51 54](https://cloud.githubusercontent.com/assets/18611095/25921352/bf83161e-35dd-11e7-8e28-b101a046ff11.png)
![2017-05-10 23 53 45](https://cloud.githubusercontent.com/assets/18611095/25921894/e2b58d36-35df-11e7-9df2-7704d067e5e6.png)
![2017-05-10 23 58 44](https://cloud.githubusercontent.com/assets/18611095/25921976/24440002-35e0-11e7-93d5-63b0bbca19bf.png)
![2017-05-11 00 28 22](https://cloud.githubusercontent.com/assets/18611095/25922172/cd728162-35e0-11e7-88f8-5362f990eb0b.png)

**Comment by sradomski** [comment]
I will retrace and report back.
