### ISSUE TITLE
Promela Datamdel: Assignment changes variable type to verbatim which later fails mathematical operation on variable of int type.

### ISSUE THREAD

**Issue by parora1701** [tklab-tud/uscxml#127]
Hello, promela datamodel from "latest" uscxml code shows following behavior:
 After assignment of a variable of type _int_ (using _expr_ attribute with type `INTERPRETED`), changes type of the variable to `VERBATIM`. hence failing any subsequent mathematical operation on the variable as it surrounds value with "/" on returning from evaluateExpr.

type of variable before assignment: 
![before_assign](https://cloud.githubusercontent.com/assets/5223842/26024484/5b314428-37d2-11e7-8ec7-0af3c80ff023.jpg)
type of variable after assignment: 
![after_assign](https://cloud.githubusercontent.com/assets/5223842/26024490/6c7ea004-37d2-11e7-901c-8067106f9ecb.jpg)

uscxml browser result: 

![result](https://cloud.githubusercontent.com/assets/5223842/26024501/9cf00af2-37d2-11e7-91b7-cb9564383d38.JPG)

following scxml can be used to test behavior: 

[test.scxml.txt](https://github.com/tklab-tud/uscxml/files/998492/test.scxml.txt)

**Comment by sradomski** [comment]
Please be so kind as to provide a simple scxml document that either end up in state `pass` or `fail` and I will get to it as soon as possible.

**Comment by parora1701** [comment]
I provided one at the bottom of the issue (please remove .txt extension). This scxml results in `pass ` if substituted with _expr_ mentioned in _comments_ otherwise it `fails ` as described in issue. 
![result_pass](https://cloud.githubusercontent.com/assets/5223842/26025074/17674cc0-37e0-11e7-9b96-b443e7c24e33.JPG)

**Comment by sradomski** [comment]
Fixed with latest commit
