### ISSUE TITLE
Error event of invalid URL in USCXMLInvoker must be rethrown 

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#130]
Hello, suppose that we are invoking source with wrong URL.
In this place we get ErrorEvent
```
void USCXMLInvoker::invoke(const std::string& source, const Event& invokeEvent) {
	if (source.length() > 0) {
		_invokedInterpreter = Interpreter::fromURL(source); // Exception is here!!!
	} else if (invokeEvent.data.node) {
```
But it is catched here
```
try {
	_callbacks->invoke(*invIter);
} catch (...) {
}
```
and user has no information about it

Source code for issue:
```
<scxml datamodel="lua" initial="s0" name="ScxmlShape1" version="1.0" xmlns="http://www.w3.org/2005/07/scxml" xmlns:conf="http://www.w3.org/2005/scxml-conformance">
	<state id="s0">
		<invoke src="INVALID_SOURCE.scxml" type="http://www.w3.org/TR/scxml"/>
		<onentry>
			<send delay="1s" event="timeout"/>
		</onentry>
		<transition event="error.*" target="pass"/>
		<transition event="*" target="fail"/>
		<transition event="done.invoke.*" target="pass2"/>
	</state>
	<final id="fail" xmlns:scxml="http://www.w3.org/2005/07/scxml">
		<onentry>
			<log expr="'fail'" label="Outcome"/>
		</onentry>
	</final>
	<final id="pass" xmlns:scxml="http://www.w3.org/2005/07/scxml">
		<onentry>
			<log expr="'pass'" label="Outcome"/>
		</onentry>
	</final>
	<final id="pass2">
		<onentry>
			<log expr="'pass2'" label="Outcome"/>
		</onentry>
	</final>
</scxml>
```

**Comment by sradomski** [comment]
I should tidy up all the throwing / catching anyway. Some exceptions are expected to be processed by the interpreter itself as an `error.platform` and I am not sure how to best handle them. Actually, you are advised to provide a topmost transition with `event="error"` and log them, but we cannot assume that every developer does so, which causes these to be hidden as mere events triggering an empty optimal transition set.

**Comment by alexzhornyak** [comment]
What about next variant for now?
```
void USCXMLInvoker::invoke(const std::string& source, const Event& invokeEvent) {
	try {		//++++++
		if (source.length() > 0) {
			_invokedInterpreter = Interpreter::fromURL(source);
		}
		else if (invokeEvent.data.node) {
			XERCESC_NS::DOMImplementation* implementation = XERCESC_NS::DOMImplementationRegistry::getDOMImplementation(X("core"));
			XERCESC_NS::DOMDocument* document = implementation->createDocument();

			// we need to import the parent - to support xpath test150
			XERCESC_NS::DOMNode* newNode = document->importNode(invokeEvent.data.node, true);
			document->appendChild(newNode);

			// TODO: where do we get the namespace from?
			_invokedInterpreter = Interpreter::fromDocument(document, _callbacks->getBaseURL(), false);
		}
		else if (invokeEvent.data.atom.size() > 0) {
			// test530 when deserializing
			_invokedInterpreter = Interpreter::fromXML(invokeEvent.data.atom, _callbacks->getBaseURL());

		}
		else {
			_isActive = false;
			ERROR_PLATFORM_THROW("Cannot invoke nested SCXML interpreter, neither src attribute nor content nor DOM is given");
		}
	}
	catch (ErrorEvent &e) { //++++++
		LOG(_callbacks->getLogger(), USCXML_ERROR) << e; //++++++
		eventToSCXML(e, USCXML_INVOKER_SCXML_TYPE, _invokeId); //++++++
		_isActive = false;  //++++++
		return;  //++++++
	}  //++++++
```

**Comment by sradomski** [comment]
The standard is not too clear here .. For now, I merely log the exception and continue - would you expect it to show up as "error.platform" in the interpreter's internal queue?

**Comment by alexzhornyak** [comment]
Yes, I would like to have similar logic, like, for example, evaluation of \<src\> in \<data\> element
**5.3.2 \<data\> children**
> If the value specified for a <data> element (by 'src', children, or the environment) is not a legal data value, the SCXML Processor must raise place error.execution in the internal event queue and must create an empty data element in the data model with the specified id.

So, I offer next logic
_if the value specified by 'src' or 'srcexpr' is not a valid URI the SCXML Processor must raise place error.execution in the internal event queue without triggering invokation_.

**Comment by sradomski** [comment]
Good point - I will do that when I have some free time.

**Comment by sradomski** [comment]
I cannot raise it as an events on the internal queue. Invokers are only processed once the internal queue is exhausted. It'd be somewhat self-defeating to raise an internal event even though the SCXML semantic guarantees that there can be none. I still log the exceptions, but would like to defer a more all-encompassing change until we have a clear use-case.
