### ISSUE TITLE
Blocking step loads CPU usage

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#132]
Hello, when we use `interpreterIter->step();`, we are getting into next loop
```
Event BasicEventQueue::dequeue(size_t blockMs) {
...
    // block for given milliseconds or until queue is non-empty
    while (endTime > std::chrono::system_clock::now() && _queue.empty()) {
        _cond.wait_until(_mutex, endTime);
    }
```
This cycle loads CPU on my Intel Core i7 per 13% for 1 interpreter. 
![2017-05-18 09 12 35](https://cloud.githubusercontent.com/assets/18611095/26188920/b170c206-3baa-11e7-9514-19830ac8e91b.png)
So if we used 8 invoking sessions with blocking step we would get 100% of CPU usage.

The solution is to let the thread sleep for a short period of time inside of the loop
```
while (endTime > std::chrono::system_clock::now() && _queue.empty()) {
    std::this_thread::sleep_for(std::chrono::microseconds(1)); // I'm not sure about the duration of sleep
    _cond.wait_until(_mutex, endTime);
}
```
![2017-05-18 09 20 36](https://cloud.githubusercontent.com/assets/18611095/26189096/7ce8dc52-3bab-11e7-9ebd-66fe3dd3af67.png)

**Comment by sradomski** [comment]
If you call step without parameters, the default is `std::numeric_limits<size_t>::max()`. Can you please confirm that `endTime` is ridiculously large when we enter the while loop? If it is indeed very very large, then someone is notifying the monitor via `enqueue(const Event& event)`.

**Comment by alexzhornyak** [comment]
![2017-05-18 10 01 48](https://cloud.githubusercontent.com/assets/18611095/26190272/3cffc83e-3bb1-11e7-998d-1d5190812154.png)

**Comment by alexzhornyak** [comment]
I'm testing this scxml
[test144.1.scxml](https://github.com/tklab-tud/uscxml/files/1010013/test144.1.scxml.txt)

**Comment by alexzhornyak** [comment]
Finally I understood that **wait_until** has unpredictable behaviour and is triggered by timeout though expire time does not come yet

![2017-05-18 10 50 50](https://cloud.githubusercontent.com/assets/18611095/26191819/0e72ba42-3bb8-11e7-8365-a8072c73fab5.png)

**Comment by sradomski** [comment]
Yes, that's why it is in a `while` loop. It is especially bad when attaching a debugger :D

**Comment by alexzhornyak** [comment]
Next code seems to work fine. I think no need to set endTime equal to max()
```
Event BasicEventQueue::dequeue(size_t blockMs) {
	std::lock_guard<std::recursive_mutex> lock(_mutex);

	if (blockMs > 0) {
		using namespace std::chrono;

		// TODO: do read http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2661.htm
		system_clock::time_point now = system_clock::now();
		system_clock::time_point endTime = now + milliseconds(blockMs);

		assert(endTime < system_clock::time_point::max());

		// block for given milliseconds or until queue is non-empty
		while (endTime > std::chrono::system_clock::now() && _queue.empty()) {			
			if (_cond.wait_until(_mutex, endTime) == std::cv_status::timeout) {
				// LOGD(USCXML_DEBUG) << "timeout expired" << std::endl;
			}
		}
	}
```

**Comment by sradomski** [comment]
The specific code segment is very carefully crafted to account for overflows. E.g. in your example `endTime` may become undefined on some platforms if `blockMs` is very large (the default).

**Comment by alexzhornyak** [comment]
We need to replace systeme_clock::time_point::max() because of [known bug](http://stackoverflow.com/questions/39041450/stdcondition-variable-wait-until-surprising-behaviour)

```
#include <iostream>
#include <chrono>
#include <cassert>
#include <thread>
#include <mutex>
#include <ctime>

int main()
{
	std::mutex mutex;
	std::condition_variable condition;

	using namespace std::chrono;

	auto forever = system_clock::time_point::max();
	std::unique_lock<std::mutex> lock(mutex);

	std::cout << "1. Try TIME_POINT MAX" << std::endl;
	condition.wait_until(lock, forever);

	std::time_t t = system_clock::to_time_t(forever); // BUG !!!
	std::time_t t_max = std::numeric_limits<std::time_t>().max();
	
	std::cout << "2. Try MORE than ULONG MAX" << std::endl;
	forever = system_clock::from_time_t(std::numeric_limits<unsigned long>().max() + 1);

	std::cout << "3. Try ULONG MAX" << std::endl;
	std::cout << "ONLY NOW WE WAIT FOREVER!" << std::endl;
	forever = system_clock::from_time_t(std::numeric_limits<unsigned long>().max());
	condition.wait_until(lock, forever);

	return 0;
}
```

**Comment by sradomski** [comment]
Fixed with latest commit. I don't wager a guess as to what's the largest timepoint any given broken `wait_until` implementation accepts, check for `blockMs = std::numeric_limits<size_t>::max()` explicitly and use `wait` without an endpoint.

Can you please check whether this solves the issue with your compiler? Also, if you still pass all tests when dropping the 200ms block in step `USCXMLInvoker.scxml`, I'd change that as well.

**Comment by alexzhornyak** [comment]
Dropping the 200ms block solves issue with my compiler. All the tests are passed the same as before.

P.S. I have some tests that I couldn't ever pass. They are platform and datamodel specific, and do not affect on my work. But if you wonder that I can not pass them, I will describe it in separate issues.

1) URL select error with endless messaging `void URLFetcher::perform()`

> w3c\lua\test201.scxml
> w3c\lua\test509.scxml
> w3c\lua\test510.scxml
> w3c\lua\test518.scxml
> w3c\lua\test519.scxml
> w3c\lua\test520.scxml
> w3c\lua\test522.scxml
> w3c\lua\test531.scxml
> w3c\lua\test532.scxml
> w3c\lua\test534.scxml
> w3c\lua\test567.scxml

2) very strange test because we can not go to 'pass' state anyway 

> w3c\lua\test301.scxml

3) we are converting tables to data and copying them, but tests expect to assigning data as pointers

> w3c\lua\test326.scxml

4) can not assign XML nodes in Lua datamodel

> w3c\lua\test530.scxml

**Comment by sradomski** [comment]
I fixed the URL select error on Win32.
