### ISSUE TITLE
V8 plugin setup

### ISSUE THREAD

**Issue by xmarduel** [tklab-tud/uscxml#133]
On centOS 7 it is unclear if cmake works correctly when trying to find the V8 libs. Typing
> cmake ..

1- It does not find the libraries (headers are found as V8_INCLUDE_DIR message is not printed):
2- It displays a wrong message concerning V8 is too old: 

-- Your V8 installation is too old - we need >= 3.23.17
-- Could NOT find V8 (missing:  V8_LIBRARY)

Which libraries should be found, and in which folder ? I have got installed in /usr/lib64 or /usr/lib64/v8
libv8_base.x64.a
libv8_nosnapshot.x64.a
libv8_snapshot.a
libicui18n.a
libicuuc.a
libicudata.a

Note that these libs are build from v8 version 3.23.17 .

**Comment by sradomski** [comment]
It did find your V8 library but could not compile the snippet from [here](https://github.com/tklab-tud/uscxml/blob/master/contrib/cmake/FindV8.cmake#L58). The file also lists all search path where `cmake` will have a look. You can also use `ccmake` and specify the paths explicitly in the GUI.

If you do not have a hard requirement on V8 but merely ECMAScript, I'd recommend JavaScriptCore as its API is way more stable. Google seem to change the V8 API every few month as a matter of principle ... There are JSC libraries distributed in the `libjavascriptcoregtk` package that you can use. Not sure though if they are in the standard CentOS repos.

**Comment by sradomski** [comment]
I will close this as there does not seem to be an issue anymore - feel free to reopen if you like to add something still.

**Comment by xmarduel** [comment]
235c235
< 	                               v8::String::New(_callbacks->getSessionId().c_str()));
---
> 	                               v8::String::New(callbacks->getSessionId().c_str()));
239c239
< 	                               v8::String::New(_callbacks->getName().c_str()));
---
> 	                               v8::String::New(callbacks->getName().c_str()));

**Comment by anibalanto** [comment]
Hello! I'm trying to compile in Debian buster with:
`cmake -DBUILD_BINDING_JAVA=OFF -DBUILD_BINDING_LUA=OFF -DBUILD_BINDING_CSHARP=OFF -DBUILD_BINDING_PYTHON=OFF ..`

it displays this message:
-- Could NOT find V8 (missing:  V8_INCLUDE_DIR)

Here [46](https://github.com/jeroen/V8/issues/46) and here [48](https://github.com/jeroen/V8/issues/48) explains that libv8-3.14 was replaced by libnode-dev in Debian. I installed it with:
'apt-get install libnode-dev'
but cmake still shows the same message.
