### ISSUE TITLE
Element <script> does not support <src> attribute

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#134]
Hello, I was really suprised that element \<script\> does not support \<src\> attribute

```
void BasicContentExecutor::processScript(XERCESC_NS::DOMElement* content) {
	// download as necessary
	std::string scriptContent(X(content->getTextContent()));
	_callbacks->eval(scriptContent);
}
```

**Comment by sradomski** [comment]
That seems like an embarrassing oversight, I will fix it in a bit - have to push new boost and mutex for uuids first.

**Comment by sradomski** [comment]
We are supposed to download scripts at [document load time](https://www.w3.org/TR/scxml/#script):

    the SCXML Processor must download the script from the specified location at load time

As such, I am required to resolve these script elements not when visiting them, but when preparing the document. I assume that this code was accidentally dropped when I introduced the `FastMicroStep` class. I will fix.

**Comment by sradomski** [comment]
Pushed
