### ISSUE TITLE
How to use custom ExecutableContent?

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#135]
Hello, I can not understand how to apply my custom ExecutableContent.
I see that I can create it and register in Factory but it is never used further in processing!? I see that it is used only in InterpeterIssue. And I get an assertion in BasicContentExecutor that my ExecutableContent is unknown.

**Comment by sradomski** [comment]
Functionality may have been dropped during the refactoring when introducing FastMicroStep and isolating the individual components. I will have a look, restore functionality and provide an example in `test-extensions`.

**Comment by sradomski** [comment]
Pushed - reopen if not satisfied. Example in `test-extensions.cpp`.

**Comment by alexzhornyak** [comment]
Thank you, everything is pretty clear
