### ISSUE TITLE
C# bindings - undefined references, logger redirect

### ISSUE THREAD

**Issue by 1aNam** [tklab-tud/uscxml#137]
Hello Stefan

I'm trying to use SWIG generated C# bindings. There are few handwritten methods in the SWIG interface file for 3 classes:
- _Event_
- _Interpreter_
- _Data_

Some of the methods don't work, though. They contain undefined references. Namely:
- _Event.getParams()_ calls non-existent getter _getParamMap()_
- _Event.setParams()_ calls non-existent getter _setParamMap()_
- _Interpreter.getIOProcessors()_ calls non-existent getter _getIOProcessorsNative()_
- _Interpreter.getInvokers()_ calls non-existent getter _getInvokersNative()_

In the case of the Event class, issue may be related to non-existent SWIG transform of source C++ multimap _params_. But I'm not sure.

So my question is: **Are these bindings supposed to work currently?**

**Speaking of C# bindings, would it be possible to provide option for setting custom action language logger in C#?** Currently SWIG transform logger into C# class _SWIGTYPE_p_Logger_ without any usable members.

**Comment by sradomski** [comment]
All of it used to work. Problem is that the C# bindings have no regression tests unlike, e.g, the Java bindings with the JEXL datamodel. I will fix it and introduce tests when I some free time. Thank you for reporting it.

**Comment by sradomski** [comment]
C# bindings fixed in latest push. I dropped most of the polishing for the generated classes as those broke, have a look at `uscxml.i` in the Java bindings if you want to reintroduce some convenience. Open a new issue for the logger please.

**Comment by 1aNam** [comment]
Thanks.

I can live without being able to manipulate _Event::params_ C++ _std::multimap_ on the bindings level. Effectively this _std::multimap_ is transformed into _event.data_. And this can be defined on the bindings level due to the fact that _Event::data_ is a std::map - convertible via SWIG into accessible C# form.

The only thing that is lost due to missing support for multimap on the bindings level is therefore option to insert duplicate keys into event's params/data. But this is non-critical. SCXML standard says in chapter B.2.8.1 _event.data that _...the Processor MUST create a property of _event.data whose name is the name of the key-value pair and whose value is the value of the key-value pair. **In the case of duplicate keys, the behavior is platform-specific.**_

Regarding the logger I'm not sure whether there is a issue at all. I was just wondering about some way to set custom logger of uscxml interpreter on the bindings level.

**Comment by sradomski** [comment]
That's ok, but for Java, we return `data.compound` as a proper `Map` and some more convenience to polish the bindings. Just be aware that I may reintroduce some of those convenience mappings for C# at some point in the future.
