### ISSUE TITLE
How to run the tests for c89.

### ISSUE THREAD

**Issue by YAziani** [tklab-tud/uscxml#138]
I've tried to run the tests for the c89 datamodel. For that I've build the program as it was described on the site linked as "Building from source" on Ubuntu 64bit. I've used the standard parameters:

_git clone git://github.com/tklab-tud/uscxml.git
mkdir uscxml/build && cd uscxml/build
cmake .. && make
mkdir -p cli && cd cli
cmake ../.. && make_

I've run the tests via
_ctest -L w3c/c89_
while being in the build folder

All other testes worked fine, but the tests for c89 were not found. The error message was:
_"No tests were found!!!"_

Trying to build the project with
_cmake -DWITH_DM_C89=YES .._ or _cmake -DWITH_DM_C89=YES ../.._
while being in the "build" or "cli" folder resulted in the following error message:

_/usr/bin/ld: deps/picoc/src/picoc-build/libpicoc.a(platform.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
deps/picoc/src/picoc-build/libpicoc.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/uscxml.dir/build.make:1662: recipe for target 'lib/libuscxml.so.2.0.0' failed
make[2]: *** [lib/libuscxml.so.2.0.0] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/uscxml.dir/all' failed
make[1]: *** [CMakeFiles/uscxml.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2_

Am I doing anything wrong, are the commands I used incorrect?

**Comment by sradomski** [comment]
As is stated in the error message, we ought to compile 'picoc' with '-fPIC'. For now, add it as a definition in 'contrib/patches/picoc/CMakeLists.txt'. I will fix it upstream later.

**Comment by sradomski** [comment]
Fixed with latest commit, pls reopen if problem persists.
