### ISSUE TITLE
Lua table order is not retained in array

### ISSUE THREAD

**Issue by sradomski** [tklab-tud/uscxml#140]

**Comment by alexzhornyak** [comment]
1. Wrong transformation from Data to Lua table.
a) we transform either _array_ or _compaund_, but table can be mixed and contains and _array_, and _compaund_
b) we can not manage key indexes in array
c) compaund index is only string but can be also integer

2. Wrong transformation from Lua table to Data
a) loosing key indexes
b) possible wrong order of array
c) possible lose of values indexed by string

**Comment by sradomski** [comment]
Solved with latest commit. Does pass your test as `test-issue140.scxml`. Please let me know if insufficient.
