### ISSUE TITLE
Inappropriate warning in validation of the <script> element

### ISSUE THREAD

**Issue by 1aNam** [tklab-tud/uscxml#141]
Interpreter validation leads to wrong warning when encountering _<script>_ element with a _src_ attribute and without any text value or children XML elements.

SCXML with such content:
`<scxml name="TestSM" initial="InitialState" xmlns="http://www.w3.org/2005/07/scxml" version="1.0" datamodel="null"><script src="SideScript.txt"/><state id="InitialState"><onenter><transition target="FinalState"/></onenter></state><final id="FinalState"/></scxml>`

referring to simple external empty script file _SideScript.txt_ (zero size, no UTF-8 BOM)

leads to positive evaluation of this condition in _InterpreterIssue.cpp_:
`if (HAS_ATTR(script, kXMLCharSource) && script->getChildNodes()->getLength() > 0) {
    issues.push_back(InterpreterIssue("Script element cannot have src attribute and children", script, InterpreterIssue::USCXML_ISSUE_WARNING));
}`

After some debugging I found that the length of the child nodes list is 1. The only element in the list is of the type _DOMNode::NodeType::TEXT_NODE_, node name _#text_ and empty node value. After putting some content in the script file, this content propagates to the node value.

**It seems that the script content from the file referred by the _src_ XML attribute is being evaluated before counting of the child nodes in the validation phase and adds to the content of the <script> element.**

The standard states: _"A conformant SCXML document MUST specify either the 'src' attribute or child content, but not both._"

I'm not sure what exactly is meant by the _child content_. Only child XML nodes? Or even the simple text XML values? If the former is true, one cannot use script element like this:
`<script src="file.js"><subnode/></script>`

Simple content would be permitted on the other hand:
`<script src="file.js">simpleTextValue</script>`

If the latter is true, only this form would be possible:
`<script src="file.js"/>`

**What is the correct interpretation in your opinion, Stefan?**

Anyway, if simple text value of the script element is permitted, the second part of the validation condition can be changed like this:
`(HAS_ATTR(script, kXMLCharSource) && script->childElementCount > 0)`

**Comment by sradomski** [comment]
When we setup the DOM, we load all external scripts and append them as text child nodes to the parent elements. We had to remove the src attribute afterwards or `validate` would report this as invalid (having both text content and a src attribute). Reopen if problem persists.
