### ISSUE TITLE
src attribute in data element wrongly parsed as XML

### ISSUE THREAD

**Issue by 1aNam** [tklab-tud/uscxml#142]
- I'm using ecmascript DM.
- There are some JSON files loaded into the context during initialization of SCXML:
`<scxml name="TEST_SM" initial="InitialState" xmlns="http://www.w3.org/2005/07/scxml" version="1.0" datamodel="ecmascript"><datamodel><data id="JSON_MainWindowMenu" src="Test.json"/></datamodel><state id="InitialState">...`
- Before fixing of issue #141 (Thanks for it!) evaluation of such data elements worked perfectly - they were interpreted as JSON.
- **But now these src attributes in the data elements are interpreted as XML which ultimately and rightfully fails in the Xerces method WFXMLScanner::scanDocument() during checking of content's prolog.**

**Comment by sradomski** [comment]
Can you provide a small SCXML + JSON file for it? Like those in the [issues folder](https://github.com/tklab-tud/uscxml/tree/master/test/issues). They end in a final state called `pass` or `fail`, depending on whether they are fixed or not. That would allow me to work on the problem right-away without any preparation or potential for ambiguities / misunderstandings.

**Comment by sradomski** [comment]
It's working great here on MacOS Sierra with clang. What's your platform and compiler?

**Comment by 1aNam** [comment]
Well everything works fine after all. I had set breakpoints on every C++ exception in Visual studio and this one Xerces SAXParseException was emerging during debug.

But now I see that you are catching these exceptions in BasicContentExecutor.

Moreover the JSON's file ANSI (non-unicode) encoding was bad for the uscxml that was slightly modified by me. When calling method `evalAsData("testData.id")` on the JSC DM and the JSON value of the id contains non-ASCII characters I was getting exception from the data JSC DM. After changing encoding of JSON into UTF-8 (without BOM) method `evalAsData` returns expected non-ASCII data without any exception. But this differs from upstream uscxml behaviour. See below.

This topic of working with non-ASCII characters across whole set of uscxml call stack (xerces, uscxml itself, JSC library) is a big one for me. When using upstream uscxml source without any modification on Windows, compiling in VS 2015, I cannot **fully** work with non-ASCII characters in JSC DM.

For example setting value of JSON's _testData.id_ to _"ü"_ and calling JSC DM equality operator _<log expr="testData.id == 'ü'"/\>_ yields **null** value for logger. When processing SCXML DOM during interpreter initialization these expressions are stored in platform's native ASCII one-byte encoding. At least on Windows. When expressions are later evaluated using method _JSCDataModel::evalAsValue_ and more precisely method _JSStringCreateWithUTF8CString_ they fail to transfer into JSString because source encoding is not UTF-8. JSC library throws an exception in this case.

Now, I managed to solve this problem by modifying methods _X(const XMLCh* const toTranscode)_ and _X(const std::string& fromTranscode)_ in DOM.h for WIN32 specific behaviour: storing content of variable __localForm_ always in UTF-8 chars and __unicodeForm_ always in UTF-16 big endian. After doing so, I can successfully run aforementioned DM evaluations and some other things.

I don't know if this quick hack is good enough but it works for me on win platform. Maybe transfering uscxml code into std::wstrings would be better...

**Comment by sradomski** [comment]
I always feared this day would come :D 

I have to admit that I ignored the issue up until now but am willing to tackle it. However, I first have to get a more precise picture as to what this would entail. My working assumption was that we can use `std::string` as mere binary containers for character encodings that use more than 8bit per character and I still somewhat do. Problem with other representation (e.g. `std::wstring`) may be the language bindings.

I'd be very much obliged if you were to send a PR with a respective test and I will see to make it happen and get an idea of what else would be required.

**Comment by sradomski** [comment]
Also, please upon up as another issue! Just copy your post, but don't mix UTF8 issues with `src attribute in data element wrongly parsed as XML` please.
