### ISSUE TITLE
Function <uscxml::toStr> inserts digit grouping symbol

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#147]
Hello, I've discovered very interesting problem.
For example, in Ukrainian locale space is the digit grouping symbol in Windows OS. And if we use uscxml::toStr function for convertation, we will get the next results:
![2017-06-22 19 47 21](https://user-images.githubusercontent.com/18611095/27445894-38781c1e-5784-11e7-95c0-d870c659901e.png)

And later we get problem, because data atom is interpreted, but, for example, Lua parser can not work with digits that have spaces inside.

**Solution:**
```
template <typename T> std::string toStr(T tmp) {
	std::ostringstream outSS;
	outSS.precision(std::numeric_limits<double>::digits10 + 1);
	outSS.imbue(std::locale("C"));
	outSS << tmp;
	return outSS.str();
}
```

**Comment by sradomski** [comment]
good catch, would you send a pull request?
