### ISSUE TITLE
invoke in a loop

### ISSUE THREAD

**Issue by xmarduel** [tklab-tud/uscxml#152]
From the code generated with uscxml-transform, it seems impossible to perform invoke statements in a loop.
Or how to achieve this ?

With with scxml example:

<?xml version="1.0" encoding="UTF-8"?>

<scxml initial="invoke_in_loop" version="0.9" xmlns="http://www.w3.org/2005/07/scxml" xmlns:ads2="http://www.xxx.com" datamodel="ecmascript">
	<datamodel>
		<data id="var1" expr="{ 'name': 'SCXML::var1', 'value':0 }" />
		<data id="counter" expr="0" />
	</datamodel>  
    
    <state id="invoke_in_loop">
        <onentry>
            <log label="invoke_in_loop" expr="'set_loop'" />
        </onentry>
        <invoke type="ads2">
            <content>
                <ads2:set name="var1" value="counter" />
            </content>
        
            <finalize>
                <log label="invoke_in_loop" expr="'at invoke_in_loop finalize...'"/>
                <assign expr="_event.data.var1" location="var1.value"/>
            </finalize>
        </invoke>
        
        <transition event="done.invoke" cond="counter == 10" target="quit_loop" >
            <log label="invoke_in_loop" expr="'transition to quit_loop ...'"/>
        </transition>
        <transition event="done.invoke"  target="invoke_in_loop" >
            <script>counter = counter + 1</script>
        </transition>
        
        <onexit>
            <log label="invoke_in_loop" expr="'on exit: var1 = ' + var1.value"/>
            <log label="invoke_in_loop" expr="'on exit: counter = ' + counter"/>
        </onexit>
    </state>
    
    <final id="quit_loop">
        <onentry>
            <log expr="'quit_loop'" />
            <log label="quit_loop" expr="'on exit: var1 = ' + var1.value"/>
            <log label="quit_loop" expr="'on exit: counter = ' + counter"/>
        </onentry>
    </final>
</scxml>

the invoke is called once, then when the transition take places, a "step" is performed and state "invoke_in_loop" is re-entered. But then the c program "freeze":

This is because in the generated C code , at the second "step", the invocations bits BIT are still set, so no
uninvoke/invoke happend, and then code waits forever for an external event

DEQUEUE_EVENT:
    if (ctx->flags & USCXML_CTX_SPONTANEOUS) {
        ctx->event = NULL;
        goto SELECT_TRANSITIONS;
    }
    if (ctx->dequeue_internal != NULL && (ctx->event = ctx->dequeue_internal(ctx)) != NULL) {
        goto SELECT_TRANSITIONS;
    }

    /* manage invocations */
    for (i = 0; i < USCXML_NUMBER_STATES; i++) {
        /* uninvoke */
        if (!BIT_HAS(i, ctx->config) && BIT_HAS(i, ctx->invocations)) {
            if (USCXML_GET_STATE(i).invoke != NULL)
                USCXML_GET_STATE(i).invoke(ctx, &USCXML_GET_STATE(i), NULL, 1);
            BIT_CLEAR(i, ctx->invocations)
        }
        /* invoke */
        if (BIT_HAS(i, ctx->config) && !BIT_HAS(i, ctx->invocations)) {
            if (USCXML_GET_STATE(i).invoke != NULL)
                USCXML_GET_STATE(i).invoke(ctx, &USCXML_GET_STATE(i), NULL, 0);
            BIT_SET_AT(i, ctx->invocations)
        }
    }

    if (ctx->dequeue_external != NULL && (ctx->event = **ctx->dequeue_external(ctx))** != NULL) {
        goto SELECT_TRANSITIONS;
    }

Could it be that a piece of code is missing at the end of the "uscxml_step" routine, something like

    ...
    // manage invocations
    for (i = 0; i < USCXML_NUMBER_STATES; i++)
    {
                BIT_CLEAR(i, ctx->invocations);
    }
    return USCXML_ERR_OK;
}

so that at the next step, the invokes statements are called once again ?

Thank you in advance.
Sincerely
XM

**Comment by sradomski** [comment]
If you are providing a custom invoker, you will have to raise `done.invoke` yourself. The implementation cannot know when your invoker is suppose to be finished. However, if you need synchronous execution, you may want to consider custom executable content. Though, I am not sure at the moment whether the ANSI-C transpilation supports it, it could be implemented though. 

Another possibility is to go for `datamodel="native"` and embed your code in `<script>` elements, it will be inserted verbatim at the corresponding place in the generated file. Also, do have a look at the examples that I link for transpilation from the front-page, i.e. the embedded case.

Does this solve your issue?

**Comment by xmarduel** [comment]
Hi,
my invoker actually raise the done.invoke event, so that the 
<finalize>
       <log label="invoke_in_loop" expr="'at invoke_in_loop finalize...'"/>
       <assign expr="_event.data.var1" location="var1.value"/>
</finalize>
is correctly run, as well as the transition -when the state is entered the first time-

datamodel="native" and embedded code in <script> is not for me an option...

**Comment by sradomski** [comment]
Can you provide me with some minimal scaffolding code? I'll prepare a test case and solve the issue then.

**Comment by xmarduel** [comment]
Hi Stefan

thank for looking at this.
I send you per mail a gzip.

Sincerely

XM

**Comment by sradomski** [comment]
Did you already send something? Didn't receive anything yet. Did it get lost?

**Comment by xmarduel** [comment]
I send a mail at 'radomski@tk.informatik.tu-darmstadt.de'

**Comment by xmarduel** [comment]
Ouups sorry: Postfach voll...
Did you get it now ?

**Comment by sradomski** [comment]
Mine inbox our yours? I did not yet receive anything.

**Comment by sradomski** [comment]
That code is not exactly minimal .. can't you break it down into something more sane for me to setup / look at? In fact it's 21,113 lines, that's plain absurd!

    $ find . -type f -exec cat {} \; |wc -l
    $ 21113

The concept here is MWE [1] with the key point being *minimal*. I am more than happy to help but if you take up all my time by requiring me to sift through tons of unnecessary boilerplate code, I would have less time to fix issues of others (let alone spend time with friends and family).

Please provide a MWE.

[1] https://en.wikipedia.org/wiki/Minimal_Working_Example

**Comment by sradomski** [comment]
I just read your question again and there may be a misconception on your part wirh regard to the semantics of invocations. They are only processed when the interpreter is stable, i.e, internal queue is empty and no spontaneous transitions enabled. That is, if you are continuously exiting and entering a state with an invoker in the same macrostep (a series of step() calls with uscxml) then you will not see any change in the invocation status of your invokers. Only the configuration at the end of a macrostep is regarded ti start/stop invokers as per standard.

**Comment by sradomski** [comment]
I am going to close this for now aIs I assume that you misunderstood the invocation semantics with regard to micro- vs. macrosteps. If this is a wrong assumption and you insist on there being an error, provide a MWE and I will fix.
