### ISSUE TITLE
test-gen-c.cpp fails for test561.scxml

### ISSUE THREAD

**Issue by xmarduel** [tklab-tud/uscxml#160]
With test561.scxml  (send event with content)

<send event="foo">
        <content>
          <books xmlns="">
            <book title="title1"/>
            <book title="title2"/>
          </books>
        </content>
</send>

the test fails.
It is because, to evaluate "_event.data.getElementsByTagName('book')[1].getAttribute('title')",
_event.data needs to be a "node", not a string. (in "execContentSend")

(I couldn't figure out how to resolve this: I always got a crash when building from the string a DOMDocument and DOMNode... and passing it to the event.data as uscxml-browser does)

**Comment by sradomski** [comment]
There is no DOM available in the transpiled case. If you need the DOM, go for interpreted mode via 'uscxml::Interpreter'. But granted, 561 ought to be ignored when running tests.
