### ISSUE TITLE
Best way to access external classes and their methods in different states?

### ISSUE THREAD

**Issue by mnambi** [tklab-tud/uscxml#169]
I have a state chart where at each state I want to call methods of a C++ class. I use the LambdaMonitor to detect if I am at a state. One option is to derive my class from the InterpreterMonitor so that it has access to the required data members and methods. Is there a better way to pass the class without creating a dependency between my class and uscxml?

**Comment by sradomski** [comment]
You can go for aggregation, that is, an instance of your class _has a_ `uscxml::Interpreter`. Then you would simply register anonymous callback functions and access the your object in the parent scope.

Another approach may be for `uscxml::Interperter::on()` (or any of the specific methods. e.g. `enterState`) to take a templated parameter or an opaque pointer which is passed into the callback function. You'd need to adapt the LambdaMonitor class if you want that.

**Comment by nurettin** [comment]
I understand the concept of aggregation, but

`you would simply register anonymous callback functions` <- I don't understand how to accomplish this. I found this code while reading the source, but it says ` @todo This is currently unsupported`

	/**
	 * Register an extension to get data into and out of the data-model.
	 * @todo This is currently unsupported
	 */
DEPRECATED virtual void addExtension(DataModelExtension* ext);

**Comment by sradomski** [comment]
For C++, there is an example right on the [front-page](https://github.com/tklab-tud/uscxml#embedded-as-a-library).

1. Instantiate a `uscxml::Interpreter`
2. On the instance, register callbacks for the various events `scxml.on().enterState(LAMBDA)`
3. Run the interpreter `while(scxml.step() != uscxml::USCXML_FINISHED)`

Did I misunderstood your problem?

**Comment by nurettin** [comment]
@sradomski Registering callbacks works perfectly. I just need to do that in `<script>var result = myObj.httpGet(someurl);</script>` where myObj is an instance of a C++ class. I want to make it a scriptable state machine, only adding javascript and scxml and it will work. When I need a new function in future state machines, I will add it to myObj.

**Comment by sradomski** [comment]
Every expression in a `<script>` element is passed over to the datamodel implementation. Unfortunately, there is no C++ datamodel and thus, no possibility to access the native objects from within `<script>` elements. They are pretty much distinct runtimes and only loosely connected as mandated by the standard. You could try to use swig to generate JS bindings for your C++ object and register it with the JS datamodel (e.g. JSC or V8). 

You can get the raw datamodel implementation from the interpreter's `ActionLanguage` and retrieve the raw implementation with some casting. Have a look at the [V8 implementation](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/plugins/datamodel/ecmascript/v8/032317/V8DataModel.cpp#L221) to get an idea on how to register swig generated entities. But as a heads-up, this is pretty involved and I cannot support you with it as uscxml pretty much lays dormant currently.

**Comment by nurettin** [comment]
I was just at the V8 implementation, and you are right. It is a bother. I think I can register Lua functions easier, provided I can get a pointer to the underlying lua interpreter from `getActionLanguage`. Thanks for the "pointer" :-)

**Comment by nurettin** [comment]
I really like uscxml because it doesn't hide internal pointers to data model and interpreter engines like Qt does. 

An alternative to my scheme would be to <send> or <raise> the event and set internal data model state within LAMBDA. That way I can emulate a callback. I can't find a way of modifying existing objects in the data model, though.

**Comment by nurettin** [comment]
Of course I can access event data within the data model so you can consider this issue closed. (I think OP was asking about the same thing)
