### ISSUE TITLE
Install fails to link against Lua 5.3.5

### ISSUE THREAD

**Issue by Phrogz** [tklab-tud/uscxml#183]
In a clean `build` directory, at the end of `cmake .. && make` I get:
```
[ 45%] Linking CXX shared library lib/libuscxml.so
/usr/bin/ld: /usr/local/lib/liblua.a(lapi.o): relocation R_X86_64_32 against `luaO_nilobject_' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/liblua.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/uscxml.dir/build.make:1769: recipe for target 'lib/libuscxml.so.2.0.0' failed
make[2]: *** [lib/libuscxml.so.2.0.0] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/uscxml.dir/all' failed
make[1]: *** [CMakeFiles/uscxml.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sradomski** [comment]
Your liblua.a was not compiled with -fPIC and cannot be linked to a shared library on x64 I am afraid. Do as the compiler tells you and `recompile with -fPIC ` please.

**Comment by Phrogz** [comment]
Thanks; I wasn't sure what `-fPIC` meant, but another developer was able to help me. I removed the Lua I had hand-built (which only builds a static library) and instead installed the `liblua5.3-dev` package to `liblua5.3.so`.
