### ISSUE TITLE
How to get list of all states in scxml-defined FSM

### ISSUE THREAD

**Issue by crichardson332** [tklab-tud/uscxml#188]
I've been using the interpreter class to implement a state machine that the user defines in scxml. I use the getConfiguration() method to get a list of all the active states in the state machine. However I also have a need to get a list of all the states in the entire state machine - not just the active ones. Is there an api for that?

**Comment by sradomski** [comment]
Well, [DOM.h](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/util/DOM.h) has a bunch of relevant methods, i.e. [filterChildElements](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/util/DOM.h#L69).

**Comment by crichardson332** [comment]
How can I get the root DOMElement pointer? The only access I have to the underlying DOM object seems to be the getConfiguration() method, but this returns a list that has already been filtered. I need access to either the full list of DOMElements from the xml file, or the root scxml tag.

**Comment by crichardson332** [comment]
Okay it works now! Thanks!
