### ISSUE TITLE
Could NOT find JSC (missing: JSC_INCLUDE_DIR JSC_LIBRARY)

### ISSUE THREAD

**Issue by eyeceeworld** [tklab-tud/uscxml#205]
when i cmake the project in Ubuntu ,it says "Could NOT find JSC (missing: JSC_INCLUDE_DIR JSC_LIBRARY)"
i download the libjavascriptcoregtk-4.0-bin by using the command "sudo apt-get install libjavascriptcoregtk-4.0-bin"
but the problem is still there, and i can't find where the jsc include file and its .so file are 
does anyone else have such a problem, any help will be appreciated

**Comment by alexzhornyak** [comment]
Have you checked the location?

![image](https://user-images.githubusercontent.com/18611095/164455930-8d7664e2-b6e4-48d8-8782-b5548a4b069d.png)

**Comment by eyeceeworld** [comment]
This problem is solved now, the path "/usr/include/webkitgtk-4.0" was missing before. "sudo apt install libjavascriptcoregtk"is not enough, "sudo apt install libwebkit2gtk-4.0-dev"should be executed before that, thanks.
