### ISSUE TITLE
Final states of parallel states

### ISSUE THREAD

**Issue by Eybor** [tklab-tud/uscxml#56]
When reaching one of the final states of a paralel state it causes the parallel state to send done.state.id directly without waiting for the other children to be in a final state. This goes against the SCXML specifications as described here : http://www.w3.org/TR/scxml/#final

**Comment by sradomski** [comment]
Could you be so kind and provide a minimal example that is self-contained and exhibits the problem? I'll get to it then.

**Comment by sradomski** [comment]
Respective code is at [InterpreterRC.cpp:297](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/InterpreterRC.cpp#L297).

**Comment by Eybor** [comment]
Here is a tiny example of what I descibed : http://s000.tinyupload.com/?file_id=21101934606763395860

**Comment by Eybor** [comment]
I think I found where the problem comes from. In https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/InterpreterRC.cpp#L305 you call internalDoneSend on the parent state, the thing is that in that function you send the event done.state with the state parent's id I think that it is what's cause the problem, in my opinion it should send this event with the state's id and not its parent.

**Comment by sradomski** [comment]
Can reproduce, will fix later today.

**Comment by sradomski** [comment]
Your code is added as a test, though without any assumptions as [test-doneevent.cpp](https://github.com/tklab-tud/uscxml/blob/master/test/src/test-doneevent.cpp). I have pushed a new commit which should have fixed the issue.

Please also observe the usage of <tt>interpreter.step()</tt> - the basic idea is that for every return value > 0, it makes sense to perform another step. Details of its semantics can be seen in [test-lifecycle.cpp](https://github.com/tklab-tud/uscxml/blob/master/test/src/test-lifecycle.cpp#L262).

**Comment by Eybor** [comment]
Thanks for your quick reaction to this issue, it now works as expected.
