### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by slavchev** [tklab-tud/uscxml#61]
I followed the [instructions](https://github.com/tklab-tud/uscxml/blob/master/docs/BUILDING.md#windows) for Windows but all it did is to generate empty project files which do not build the source code itself. Any ideas how to proceed?

**Comment by sradomski** [comment]
CMake will create project files for Visual Studio, you can then open them with Visual Studio 2010 and build them. If you choose anything more recent than Visual Studio 2010, you will have to provide prebuild libraries in contrib/prebuilt/<compiler_ID>.

Did CMake not generate project files or do the project files not contain any meaningful projects? Sometimes you have to hit "Configure" twice within the CMake-GUI until everything is setup. If this does not solve your issue, try to post more details please.

**Comment by slavchev** [comment]
>If you choose anything more recent than Visual Studio 2010, you will have to provide prebuild libraries (e.g. for libcurl, libevent) in contrib/prebuilt/.

Yes, I figured it out. I use VS 2015 and after I examined the CMake scripts I changed them a bit to fit my scenario. So far everything works as expected. Maybe I will create a pull request latter if I have time. Feel free to close this issue.

**Comment by sradomski** [comment]
Pull request would be appreciated, thank you
