### ISSUE TITLE
Assertion failed in Interpreter destructor after testing <invoke> element

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#62]
I'm trying to test procedure according to standard as described here _If the invoking session takes a transition out of the state containing the <invoke> before it receives the 'done.invoke.id' event, the SCXML Processor must automatically cancel the invoked component and stop its processing_

[main.scxml](https://www.dropbox.com/s/e4rvm2omoqjxs01/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-04-22%2012.05.37.png?dl=0)

[invoke content scxml](https://www.dropbox.com/s/fzbohzj38375u0o/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-04-22%2012.07.34.png?dl=0)

[full source code](https://www.dropbox.com/s/3ai1esk6r8mfcdl/test_invoke_transition.cpp?dl=0)

So, the problem is that, when invoke content finished normally and we finished after 'done.invoke.id' event, Inerpreter object can be deleted without any problems. But, when we are in some middle state inside invoke content scxml and then we receive transition out, after finishing state machine in InterpreterImpl::~InterpreterImpl() we get assertion.

[Screenshot of problem](https://www.dropbox.com/s/r5hoku9xpjsv1o9/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-04-22%2012.16.41.png?dl=0)

**Comment by sradomski** [comment]
I have submitted your issue as [test-issu62.cpp](https://github.com/tklab-tud/uscxml/blob/master/test/src/issues/test-issue62.cpp). The easiest solution for you is to use blocking steps in line 64 by passing true to step():

        while(state != uscxml::USCXML_FINISHED) {
            do {
                state = scxml.step(true);
            } while(state > 0);
        }

Let me know if this did not solve your problem.
