### ISSUE TITLE
XML Character escaping entity '&quot;' is ignored by xml parser (Lua datamodel)

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#63]
Suppose we have some variants of text in script:
1) `"<script> print('Hello, World!') </script>"`
Output>>`print('Hello, World!')`    Ok.

2) `"<script> print("Hello, World!") </script>"`
Output>>`print("Hello, World!")`    Ok.

3) `"<script><![CDATA[ print('Hello, \"World\"') ]]> </script>"`
Output>>:`print('Hello, "World!"')`    Ok.

4) `"<script> print('Hello, &quot;World&quot;') </script>"`
Output>>:`print('Hello, World!')`    Error!
Description: missing double quotes around 'World'!

5) `"<script> print(&quot;Hello, world!&quot;) </script>"`
Output>>: `print(Hello, world!)`    Fatal!
Description: missing double quotes and of course Lua syntax error

As far as you know a lot of parsers enclose double quotes in attributes and text with entity "&quot". And after creating scxml text we have all double quotes escaped. What is the correct way to manage with text attributes, that contains such entities?

[source code for testing](https://www.dropbox.com/s/83ze25zohh556q9/test_script_double_quotes.cpp?dl=0)

**Comment by alexzhornyak** [comment]
Also, for example, we have transition with next condition
`<transition cond="_event.data==&quot;string value&quot;" event="test" target="FinalShape1"/>`

It has absolutely correct syntax and working well in uscxml interpreter, but during checking issues by validating, we've got message 
_Issue (WARNING) at //state[@id="init"]/transition[1]: Syntax error in cond attribute_

**Comment by sradomski** [comment]
Ok, I have added it as [test-issue63.cpp](https://github.com/tklab-tud/uscxml/blob/master/test/src/issues/test-issue63.cpp) and I am seeing different output!

    print('Hello, World!')                   -> Hello, World!
    print(\"Hello, World!\")                 -> Hello, World!
    print('Hello, &quot;World&quot;')        -> Hello, "World"
    <![CDATA[ print('Hello, \"World\"') ]]>  -> Hello, "World"
    print(&quot;Hello, world!&quot;)         -> Hello, world!

The examples are from your linked source code - can you confirm that you still get the error with <tt> test-issue63</tt>? As for the warning with the syntax error from <tt>validate()</tt>, that's a bug I will fix once we have this sorted out.

**Comment by alexzhornyak** [comment]
I'm using static library of uscxml, that was built from source downloaded as zip file aproximately a week ago.
Now I'm still having a problem.
[screenshot](https://www.dropbox.com/s/rmog1agorfzx1il/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-04-22%2018.49.05.png?dl=0)

What is latest version of library? Is it normal to download from zip or is better to update from git?

**Comment by sradomski** [comment]
Hmm, my guess is the XML parser on Win32. I will check as soon as I have access to a MSVC2010 compiler.

**Comment by sradomski** [comment]
Can confirm with Visual Studio 10 output is:

    print('Hello, World!')                   -> Hello, World!
    print(\"Hello, World!\")                 -> Hello, World!
    print('Hello, &quot;World&quot;')        -> Hello, World
    <![CDATA[ print('Hello, \"World\"') ]]>  -> Hello, "World"
    print(&quot;Hello, world!&quot;)         -> 
        error.execution: [string \"             print(Hello, world!)        \"]:1: ')' expected near '!'

This is unfortunate, but I am in the latest stages of replacing Arabica with XercesC anyway so I will not correct this one for now and hope it vanishes with xercesc.
