### ISSUE TITLE
Wrong URL causes crash on VC2010 Windows 7.1 64

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#66]
During executing **test-url.exe** application crashes on lines 
`absURLs.push_back(URL("file:/"));`
`relURLs.push_back(URL("file:"));`

Exact place in **URL.cpp**
`_uri = Arabica::io::URI(url);`

And on lines
```
URL relURL(*relIter);
relURL.toAbsolute(*absIter);
```
when `relURL=="file://"`

Thus, for example, I can not pass test216.scxml.
```
<scxml datamodel="lua" initial="s0" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<datamodel>
		<data expr="'foo'" id="testvar1"/>
	</datamodel>
	<state id="s0">
		<onentry>
			<send delay="5s" event="timeout"/>
			<assign expr="'file:test216sub1.scxml'" location="testvar1"/>
		</onentry>
		<invoke srcexpr="testvar1" type="http://www.w3.org/TR/scxml"/>
		<transition event="done.invoke" target="pass"/>
		<transition event="*" target="fail"/>
	</state>
	<final id="pass"/>
	<final id="fail"/>
</scxml>
```
`expr="'file:test216sub1.scxml'"` - CRASH
`expr="'test216sub1.scxml'"` - CRASH
`expr="'file:///test216sub1.scxml'"` - Error>"Failed to create interpreter from file:///test216sub1.scxml"

`expr="'g:\\SDK\\uscxml_git\\test\\w3c\\lua\\test216sub1.scxml'"` 
- Error>"Failed to create interpreter from file://g/SDK/uscxml_git/test/w3c/lua/test216sub1.scxml"

`expr="'g:/SDK/uscxml_git/test/w3c/lua/test216sub1.scxml'"` 
- Error>"Failed to create interpreter from file://g/SDK/uscxml_git/test/w3c/lua/test216sub1.scxml"

`expr="'file:///g:/SDK/uscxml_git/test/w3c/lua/test216sub1.scxml'"` - WORKS

**Comment by sradomski** [comment]
Fixed
