### ISSUE TITLE
Element <finalize> with no executable content do not update model data.

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#67]
According to standard in the chapter 6.5.2 of element \<finalize\> is written

> If no executable content is specified, the SCXML Processor must update the data model each time an event is received from the child process that was created by the parent <invoke> element. Specifically if the parent <invoke> element contains a 'namelist' attribute or one or more <param> children containing 'location' attributes, then for each item in the 'namelist' attribute and each such <param> element, the Processor must update the corresponding location as if by <assign> with any return value that has a name that matches the 'namelist' item or the 'name' of the <param> element. Thus the effect of an <invoke> with an empty <finalize> element and either a 'namelist' attribute or a <param> element with a 'location' attribute is first to send the part of the data model specified by 'namelist' or 'location' to the invoked component and then to update that part of the data model with any returned values that have the same name. Note that the automatic update does not take place if the <finalize> element is absent as opposed to empty.

So the next scxml fails 
```
<scxml datamodel="lua" initial="main" name="root" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<datamodel>
		<data expr="1" id="i_GLOBAL_VAR"/>
	</datamodel>
	<state id="main" initial="start">
		<transition event="error.*" target="Fail"/>
		<transition cond="i_GLOBAL_VAR==2" event="completed" target="Pass"/>
		<transition event="completed" target="Fail"/>
		<state id="start">
			<invoke id="test_invoke" namelist="i_GLOBAL_VAR" type="scxml">
				<content>
					<scxml datamodel="lua" initial="InvokeStart" name="scxml_invoke" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
						<datamodel>
							<data expr="0" id="i_GLOBAL_VAR"/>
						</datamodel>
						<final id="InvokeEnd">
							<onentry>
								<send event="completed" namelist="i_GLOBAL_VAR" target="#_parent"/>
							</onentry>
						</final>
						<state id="InvokeStart">
							<onentry>
								<assign expr="i_GLOBAL_VAR*2" location="i_GLOBAL_VAR"/>
								<log expr="i_GLOBAL_VAR" label="INVOKE-i_GLOBAL_VAR"/>
							</onentry>
							<transition target="InvokeEnd"/>
						</state>
					</scxml>
				</content>
				<finalize/>
			</invoke>
		</state>
	</state>
	<final id="Fail"/>
	<final id="Pass"/>
</scxml>
```

**Comment by sradomski** [comment]
Wow, I read the specification countless times, but this specific stanza always eluded me - it's implemented in the latest git push.
