### ISSUE TITLE
Assertion in case of using send with id

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#68]
I'm testing of canceling events. And I've got assertion

`Assertion failed: _sendIds.find(sendReq.sendid) == _sendIds.end(), file ..\src\uscxml\Interpreter.cpp, line 2117`

in scxml below

```
<scxml datamodel="lua" initial="work" name="root" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<datamodel>
		<data expr="0" id="testvar1"/>
	</datamodel>
	<state id="work" initial="act1">
		<transition event="OnTimer" target="fail"/>
		<transition cond="testvar1&gt;3" target="Pass"/>
		<state id="act1">
			<onentry>
				<send delay="3000ms" event="OnTimer" id="ID_OnTimer"/>
				<send delay="300ms" event="OnDone"/>
				<assign expr="testvar1 + 1" location="testvar1"/>
			</onentry>
			<onexit>
				<cancel sendid="ID_OnTimer"/>
			</onexit>
			<transition event="OnDone" target="act2"/>
		</state>
		<state id="act2">
			<onentry>
				<send delay="1000ms" event="Back"/>
			</onentry>
			<transition event="Back" target="act1"/>
		</state>
	</state>
	<final id="fail"/>
	<final id="Pass"/>
</scxml>
```

**Comment by alexzhornyak** [comment]
And even without cancelling I can not understand why we aren't able to resend event with id, like in the example below
```
<scxml datamodel="lua" initial="act1" name="ScxmlShape1" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<datamodel>
		<data expr="0" id="testvar1"/>
	</datamodel>
	<state id="act2">
		<transition target="act1"/>
	</state>
	<state id="act1">
		<onentry>
			<send delay="2000ms" event="OnTimer" id="ID_OnTimer"/>
			<send delay="300ms" event="OnDone"/>
			<assign expr="testvar1 + 1" location="testvar1"/>
		</onentry>
		<transition event="OnDone" target="act2"/>
		<transition cond="testvar1&gt;1" target="Pass"/>
	</state>
	<final id="Pass"/>
</scxml>
```

If we will not use send id, it will works
```
<scxml datamodel="lua" initial="act1" name="ScxmlShape1" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<datamodel>
		<data expr="0" id="testvar1"/>
	</datamodel>
	<state id="act2">
		<transition target="act1"/>
	</state>
	<state id="act1">
		<onentry>
			<send delay="2000ms" event="OnTimer"/>
			<send delay="300ms" event="OnDone"/>
			<assign expr="testvar1 + 1" location="testvar1"/>
		</onentry>
		<transition event="OnDone" target="act2"/>
		<transition cond="testvar1&gt;1" target="Pass"/>
	</state>
	<final id="Pass"/>
</scxml>
```

**Comment by sradomski** [comment]
Hmm, the imterpreter is complaining about send identifiers being reused before the events were dispatched. I am not sure about the correct behavior here. Wouldn't you expect send identifiers to be unique - otherwise canceling might also affect multiple pending send requests. Simplest solution might be a multimap, but I will have to think about it for a bit.

**Comment by alexzhornyak** [comment]
But what about first example.
1) enter "act1", send "OnTimer" with id "ID_OnTimer"
2) exit "act1", cancel "ID_OnTimer" (I suppose that 'ID_OnTimer' must be removed from the queue)
3) go to "act2" and back
4) enter "act1" and "ID_OnTimer" (Assertion that means 'ID_OnTimer' is present in queue! Why?)

**Comment by sradomski** [comment]
Ok, I fixed the first part of the issue. Still the question is what to do if we enqueue two send requests with the same identifier? Did you find anything in the specs in this regard?

**Comment by sradomski** [comment]
The text from the W3C recommendation suggests to merely enqueue send requests with the same identifier and have a respective cancel to delete them all. I will implement when I am back on a desk.

**Comment by alexzhornyak** [comment]
According to spec _\<cancel\> 6.3.1 Attribute Details_

 > if multiple delayed events have this sendid, the Processor will cancel them all

So, I think that multiple delayed events are allowed and example below must work.
```
<send delay="2000ms" event="OnTimer" id="ID_OnTimer"/>
<send delay="300ms" event="OnDone"/>
```

But according to spec _3.14 IDs_

> The ids for \<send\> and \<invoke\> are subtly different. In a conformant SCXML document, they must be unique within the session...

I offer to add issue checking whether they are unique, because now no warning or error on issue checking (see example below).
```
<send delay="2000ms" event="OnTimer" id="ID_OnTimer"/>
<send delay="300ms" event="OnDone" id="ID_OnTimer"/>
```

**Comment by sradomski** [comment]
fixed
