### ISSUE TITLE
Ubuntu 15.10: can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by c64zottel** [tklab-tud/uscxml#72]
Hello,

i just tried the new version. I get now:
Is there a flag missing?
can not be used when making a shared object; recompile with -fPIC

[ 32%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/interpreter/ContentExecutorImpl.cpp.o
[ 33%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/interpreter/MicroStepFast.cpp.o
[ 35%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/interpreter/EventQueueImpl.cpp.o
[ 37%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/interpreter/InterpreterImpl.cpp.o
[ 39%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/messages/Event.cpp.o
[ 41%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/messages/Blob.cpp.o
[ 43%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/messages/Data.cpp.o
[ 45%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/debug/InterpreterIssue.cpp.o
[ 47%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/util/Convenience.cpp.o
[ 49%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/util/DOM.cpp.o
[ 50%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/util/Predicates.cpp.o
[ 52%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/util/URL.cpp.o
[ 54%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/util/UUID.cpp.o
[ 56%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/util/String.cpp.o
[ 58%] Building C object CMakeFiles/uscxml.dir/src/uscxml/util/MD5.c.o
[ 60%] Building C object CMakeFiles/uscxml.dir/src/uscxml/util/Base64.c.o
[ 62%] Building C object CMakeFiles/uscxml.dir/src/uscxml/util/SHA1.c.o
[ 64%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/server/HTTPServer.cpp.o
[ 66%] Building C object CMakeFiles/uscxml.dir/contrib/src/jsmn/jsmn.c.o
[ 67%] Building C object CMakeFiles/uscxml.dir/contrib/src/evws/evws.c.o
[ 69%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/Interpreter.cpp.o
[ 71%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/plugins/Factory.cpp.o
[ 73%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/plugins/datamodel/null/NULLDataModel.cpp.o
[ 75%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/plugins/invoker/scxml/USCXMLInvoker.cpp.o
[ 77%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/plugins/ioprocessor/scxml/SCXMLIOProcessor.cpp.o
[ 79%] Building CXX object CMakeFiles/uscxml.dir/src/uscxml/plugins/ioprocessor/basichttp/BasicHTTPIOProcessor.cpp.o
Linking CXX shared library lib/libuscxml.so
/usr/bin/ld: deps/uriparser/lib/liburiparser.a(UriFile.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
deps/uriparser/lib/liburiparser.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/uscxml.dir/build.make:718: recipe for target 'lib/libuscxml.so.2.0.0' failed
make[2]: *** [lib/libuscxml.so.2.0.0] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/uscxml.dir/all' failed
make[1]: *** [CMakeFiles/uscxml.dir/all] Error 2
Makefile:85: recipe for target 'all' failed
make: *** [all] Error 2
orko@battlecat:~/study/t

**Comment by sradomski** [comment]
Well, obviously -fPIC is missing =)
I tried on Debian Jessie 64Bit and it worked - strange. Will try to recreate before fixing. You can have a look at contrib/cmake/BuildURIParser.cmake to force some flags upon configure until I fixed it.

**Comment by sradomski** [comment]
Fixed, clean build dir and retry - please reopen if you still have issues
