### ISSUE TITLE
Can not build 'libcurl' win 7 64 VS2013

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#73]
> CMake Error at libcurl-stamp/download-libcurl.cmake:9 (file):
> file DOWNLOAD HASH mismatch
> for file: [G:/SDK/uscxml_2_0/vc12/deps/libcurl/src/curl-7.48.0.tar.gz]
> expected hash: [b2cac71029d28cb989150bac72aafab5]
> actual hash: [d41d8cd98f00b204e9800998ecf8427e]
> status: [51;"SSL peer certificate was not ok"]

P.S. It's a pity that you did not support more VS2010

**Comment by sradomski** [comment]
File checksum mismatch and invalid peer certificate? It's either a proxy forced on you or a man in the middle attack. I will not fix. 

With regard to VS2010 and MSVC16: we decided to use a conservative subset of the C++11 standard. It was just too tempting to have lambdas, std::thread and auto types available. As google's v8 made a similar mive earlier, we thought the time right.

**Comment by alexzhornyak** [comment]
It's strange but problem is only with 'libcurl', all other extern libs are downloaded normally :(

**Comment by sradomski** [comment]
The file is also available per http, which will get you around the supposedly invalid peer certificate. Substitute `https://curl.haxx.se/download/curl-7.48.0.tar.gz` by `http://curl.haxx.se/download/curl-7.48.0.tar.gz` and see whether this is any better? I'd be willing to drop https as we do still verify via checksums.

**Comment by alexzhornyak** [comment]
'http' does not help. I think that may be this is cmake problem because I can download it manually either 'https' or 'http'.
Later I will check on another computer to understand is this local problem or not.

**Comment by sradomski** [comment]
I could not reproduce on any other host and will postulate that the checksum is indeed correct and someone is delivering you the wrong file. You can always adapt BuildLibCurl.cmake locally but https://curl.haxx.se/download/ is indeed the authorative source for libcurl.
