### ISSUE TITLE
'getopt.c' not included in uscxml.lib (Win 7.1)

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#76]
That's why during compiling app we get errors

> uscxml.lib(Interpreter.obj) : error LNK2001: unresolved external symbol _getopt_long_only
> uscxml.lib(Interpreter.obj) : error LNK2001: unresolved external symbol _optind
> uscxml.lib(Interpreter.obj) : error LNK2001: unresolved external symbol _opterr
> uscxml.lib(Interpreter.obj) : error LNK2001: unresolved external symbol _optarg

**Comment by sradomski** [comment]
Exactly the problem I am at now myself :)

**Comment by sradomski** [comment]
fixed
