### ISSUE TITLE
Can not resolve URL (Win 7.1 MSVC2013)

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#77]
During executing 'test-validating.cpp' in line `Interpreter interpreter = Interpreter::fromXML(xml, "")`
I've got exception in 'url.cpp' function 'resolve'

> Cannot resolve \<\> with \<file%3A%2F%2FG%3A/SDK/uscxml_2_0/vc12/test/\>

**Comment by alexzhornyak** [comment]
For now, I've found a working variant. Pass the working dir in windows URL format as the second argument like this
`Interpreter interpreter = Interpreter::fromXML(xml, "file:///G:/SDK/uscxml_2_0/vc12/test/");`

**Comment by sradomski** [comment]
Problem was in URLImpl::resolveWithCWD. Evidently, we may not have the file:// prefix on windows platforms. In any case, it is fixed now.
