### ISSUE TITLE
uriparser no copied / missing xercesc headers not detected

### ISSUE THREAD

**Issue by c64zottel** [tklab-tud/uscxml#78]
Hello,

thx for the quick fixes.
uriparser is not copied during installation and missing header files for libxercesc are not detected. (not sure if you care about that)

**Comment by sradomski** [comment]
Yes, realized that as well. I will need to remove any 3rd-party includes from the public uscxml headers. Respective tests are already in place, we just need to get serious about PIMPL and only forward declare the implementations. Will do so during the weekend.

**Comment by sradomski** [comment]
We will make every attempt, not to rely on the uriparser / xercesc headers in the public part of our API. If, at times, it is not possible to get away with a forward declaration or hide the respective types, we will have to reevaluate the approach. I would, very much, like to avoid to install 3rd party headers.
