### ISSUE TITLE
Forward declaration instead of include? 

### ISSUE THREAD

**Issue by c64zottel** [tklab-tud/uscxml#80]
Hello,
I guess, it's still necessary to use the Factory when creating IOProcessors.
but Factory.h includes:
#include "uscxml/InterpreterInfo.h"
which further needs XPath.hpp

but the include is not necessary in Factory.h, forward decl would be sufficient.

usr/local/include/uscxml -I. -o ustatemachine.o ../bitbucket/libs/uscxmlManager/ustatemachine.cpp
In file included from /usr/local/include/uscxml/Factory.h:24:0,
                 from ../bitbucket/libs/uscxmlManager/ustatemachine.cpp:4:
/usr/local/include/uscxml/InterpreterInfo.h:28:27: fatal error: XPath/XPath.hpp: No such file or directory
compilation terminated.

**Comment by sradomski** [comment]
I have not yet finished up on the forward declarations - pull requests are appreciated. Please also augment the public header tests at https://github.com/tklab-tud/uscxml/blob/master/test/CMakeLists.txt#L74

**Comment by sradomski** [comment]
Ok, I have forward included as much as is possible (I think). If there is still intermingling of private and public headers, open a new issue pls
