### ISSUE TITLE
Syntax error in 'test\CMakeLists.txt'

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#81]
Error on string 72:	
`FILE(WRITE ${CMAKE_CURRENT_BINARY_DIR}/headers/${USCXML_REL_HEADER}.cpp ${HEADER_TEST})`

> CMake Error at test/CMakeLists.txt:72 (FILE):
>   file Internal CMake error when trying to open file:
>   G:/SDK/uscxml_2_0/vc12/test/headers/G:/SDK/uscxml_2_0/src/uscxml/uscxml.h.cpp
>   for writing.

**Comment by sradomski** [comment]
Was already fixed this morning
