### ISSUE TITLE
Syntax error in 'BuildXercesC.cmake'

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#82]
On string 57 and 72 we need slash in copy destination directory. Otherwise cmake creates file with such name

Wrong variant:
`${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/deps/xerces-c/lib/xerces-c_3_1.dll ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}`

Correct variant
`${CMAKE_COMMAND} -E copy ${CMAKE_BINARY_DIR}/deps/xerces-c/lib/xerces-c_3_1.dll ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/`

P.S. And please, look at issue 75. It needs more correction.

**Comment by sradomski** [comment]
Fixed, thank you! Missed that as the directory already existed when I tested

**Comment by sradomski** [comment]
If you feel issue75 is still a problem, please reopen and post a more detailled description. It works as intended on my Windows 7 with VS2012.
