### ISSUE TITLE
[Lua datamodel] Script content is evaluated with 'return' that causes error

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#83]
Hello, script code seems to be evaluated as data.

```
<scxml datamodel="lua" initial="Start" name="Root" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<state id="Start">
		<onentry>
			<script>x = 15
print(string.format(&quot;x=%d&quot;,x))
			</script>
		</onentry>
		<transition target="Pass"/>
	</state>
	<final id="Pass"/>
</scxml>
```

On version 1.0 it works normally, but now I've got syntax error.

> 2016-06-13 15:53:17,176 ERROR [default]     name: error.execution
>     data: 
>   {
>     "cause": "[string \"return(x = 15...\"]:1: ')' expected near '='"
>   }

**Comment by sradomski** [comment]
Fixed
