### ISSUE TITLE
Alternative way for pause in uscxml interpreter

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#90]
Hello,
USCXML is a great library for supporting scxml standard, but there is a real problem for modelling difficult systems, especially during some simulations. Because we need pause/resume mode.
SCXML offers history states for this purposes. But modelling in such case becomes redundant and difficult.
Let's take a look at simple example.
```
<scxml initial="Flash" name="ScxmlShape1" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<state id="Flash" initial="ApuOff">
		<transition event="error.*" target="Fail"/>
		<transition event="StopExercise" target="Pass"/>
		<state id="ApuOn">
			<onentry>
				<send delay="2000ms" event="DoApuOff" id="ID_DoApuOff"/>
			</onentry>
			<transition event="DoApuOff" target="ApuOff"/>
		</state>
		<state id="ApuOff">
			<onentry>
				<send delay="2000ms" event="DoApuOn" id="ID_DoApuOn"/>
			</onentry>
			<transition event="DoApuOn" target="ApuOn"/>
		</state>
	</state>
	<final id="Fail"/>
	<final id="Pass"/>
</scxml>
```
What we should do if we needed pause/resume?
```
<scxml datamodel="lua" initial="StateShape1" name="ScxmlShape1" version="1.0" xmlns="http://www.w3.org/2005/07/scxml">
	<final id="Fail"/>
	<state id="StateShape1" initial="Flash">
		<transition event="error" target="Fail"/>
		<transition event="StopExercise" target="Pass"/>
		<state id="Flash">
			<datamodel>
				<data id="t_ApuOff">{
    dDiff = 0,
    dEnter = os.clock(),
    dInterval = 2000
}
				</data>
				<data id="t_ApuOn">{
    dDiff = 0,
    dEnter = os.clock(),
    dInterval = 2000
}
				</data>
				<data expr="'xxx'" id="FlashName"/>
			</datamodel>
			<transition event="Pause" target="OnPause"/>
			<state id="ApuOn">
				<onentry>
					<send delayexpr="tostring(t_ApuOn.dInterval-t_ApuOn.dDiff)..'ms'" event="DoApuOff" id="ID_DoApuOff"/>
					<assign expr="os.clock()" location="t_ApuOn.dEnter"/>
					<log expr="string.format('%s=%d',FlashName,t_ApuOn.dInterval-t_ApuOn.dDiff)" label="Delay[On]"/>
				</onentry>
				<onexit>
					<cancel sendid="ID_DoApuOff"/>
					<assign expr="t_ApuOn.dDiff + (os.clock() - t_ApuOn.dEnter)*1000" location="t_ApuOn.dDiff"/>
					<log expr="string.format('%s=%d',FlashName,t_ApuOn.dDiff)" label="Elapsed[On]"/>
				</onexit>
				<transition event="DoApuOff" target="ApuOff">
					<assign location="t_ApuOn.dDiff" expr="0"/>
				</transition>
			</state>
			<initial>
				<transition target="ApuOff">
					<assign location="t_ApuOff.dDiff" expr="0"/>
					<assign location="t_ApuOn.dDiff" expr="0"/>
				</transition>
			</initial>
			<state id="ApuOff">
				<onentry>
					<send delayexpr="tostring(t_ApuOff.dInterval-t_ApuOff.dDiff)..'ms'" event="DoApuOn" id="ID_DoApuOn"/>
					<assign expr="os.clock()" location="t_ApuOff.dEnter"/>
					<log expr="string.format('%s=%d',FlashName,t_ApuOff.dInterval-t_ApuOff.dDiff)" label="Delay[Off]"/>
				</onentry>
				<onexit>
					<cancel sendid="ID_DoApuOn"/>
					<assign expr="t_ApuOff.dDiff + (os.clock() - t_ApuOff.dEnter)*1000" location="t_ApuOff.dDiff"/>
					<log expr="string.format('%s=%d',FlashName,t_ApuOff.dDiff)" label="Elapsed[Off]"/>
				</onexit>
				<transition event="DoApuOn" target="ApuOn">
					<assign location="t_ApuOff.dDiff" expr="0"/>
				</transition>
			</state>
			<history id="HistoryShape1" type="deep">
				<transition target="ApuOff"/>
			</history>
		</state>
		<state id="OnPause">
			<transition event="Resume" target="HistoryShape1"/>
		</state>
	</state>
	<final id="Pass"/>
</scxml>
```
Our simple example becomes a monster and if we will use invokable processes we need to send event 'Pause' to all timers and to create a lot of conditions.

So what is my offer?
If I'm not mistaken, uscxml uses libevent library for events and for timers it use 'evutils_gettimeofday' function. That's why the simpliest way is to give an opportunity for user to override global time with custom global timer.

It would be very great to have some function of pause/resume in uscxml interpreter.

**Comment by sradomski** [comment]
You can already subclass the [EventQueue](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/EventQueue.h) and add whatever functions you like. Currently though, I am still [statically allocating a BasicEventQueue instance](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/InterpreterImpl.cpp#L207) and there is nowhere for you to register your subclassed instance. 

There are two approaches for you to provide your own, none of which are implemented yet:
   
   1. Move that responsibility into the Factory and register your subclass there, same as with the [Datamodel](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/plugins/Factory.h#L56).

   2. Pass an instance as part of the [ActionLanguage](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/Interpreter.h#L175) object, but then the problem is to instantiate new instances for invoked interpreters.

I guess the best approach would be for all instances contained in an interpreter's ActionLanguage to feature factory methods to instantiate new objects of themselves. This way we can use the ActionLanguage of our parent Interpreter to get new instances for invoked Interpreters. 

Opinions?

**Comment by alexzhornyak** [comment]
I can only say that it must affect on all instances of all invoked interpreters. The way of implementation is on your decision.  I need something like this:

```
int CustomGetTimeOfDay(struct timeval *tv, struct timezone *tz)
{
	struct _timeb tb;

	MyCustomTimeFunction(&tb);
	
	tv->tv_sec = (long) tb.time;
	tv->tv_usec = ((int) tb.millitm) * 1000;
	return 0;
}

Factory::getInstance()->registerCustomTimer(&CustomGetTimeOfDay);
```

**Comment by sradomski** [comment]
I will now allow to pass an instance of a subclass of [DelayedEventQueue](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/EventQueue.h#L52) to an interpreter instance via [setActionLanguage()](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/Interpreter.h#L175) (the delayedQueue field of the ActionLanguage object). The [default implementation](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/interpreter/BasicEventQueue.cpp#L76) is realized with libevent and there is no language feature with libevent to pause the event loop. 

Thus, if you like to pause the delivery of delayed events, you will have to implement a custom DelayedEventQueue with such a feature. If you merely like to pause the interpreter, just do not call step() any more (which will still enqueue delayed events with the default implementation).

If you have any other idea, feel free to reopen and propose them.
