### ISSUE TITLE
to serialize and deserialize the state SCXML file

### ISSUE THREAD

**Issue by EduardShaid** [tklab-tud/uscxml#93]
whether the program uscxml is able to serialize and deserialize (save and restores) the state SCXML file?

**Comment by sradomski** [comment]
The problem with serializing the *complete* state of an interpreter instance is the state of the embedded data-model. It is, generally, not possible to serialize the state of an embedded JavaScriptCore instance or a Google V8 engine for that matter. Thus, we cannot (de-)serialize the state of an interpreter. We used to support an API to set an interpreters configuration, but this will not restore the state of the embedded data-model. If it is sufficient for your case to have the interpreter restore its configuration, let me know and I will add those functions again.

**Comment by EduardShaid** [comment]
If embedded data-model will also Lua, is it possible to solve this problem completely ?
If so, how this task is implemented ?

Thank you !

**Comment by sradomski** [comment]
No, at runtime, I do have an instance of a [lua_State](https://github.com/tklab-tud/uscxml/blob/master/src/uscxml/plugins/datamodel/lua/LuaDataModel.h#L89) and as far as I can tell, there is no API provided by Lua to serialize this state and restore it at a later time.

There maybe some kludges to serialize at least Lua tables and restore them at a later time. I will have to give it some thought.

**Comment by EduardShaid** [comment]
Well, no need to rush.

**Comment by sradomski** [comment]
I thought about this long and hard and can only see only one approach that would be applicable to all datamodels: The interpreter will offer a new function `suspend()` that will trigger a `platform.suspend` event and an accompanying I/O processor that is available to receive an event from SCXML whose associated data contains all the serializable state of the data-model. This I/O processor would receive the suspend event with the data-models state, read the interpreters configuration, history assignments and late binding status for datas and serialize it all into a byte array. You could then safe the byte array in the filesystem or send it via the network to another host. To resume an interpreter, you will have a new static Interpreter method fromState(char*) which will reconfigure an interpreter with regard to its configuration, history assignment and late-binding status and redeliver the event that you sent to the I/O processor earlier to allow an SCXML author to reinitialize the data-model.

This has a number of advantages:
- Serializing the data-model state as a data associated with an event will allow us to instantate on another interpreter that potentially uses another data-model
- Including the interpreters state will allow us to terminate the complete uSCXML runtime in between

But also some disadvantages:
- The SCXML author has to be aware of the approach and will need transitions for the `platform.suspend` and `platform.resume` events in the topmost SCXML state to reinitialize the data-models variables
- We cannot suspend lambdas or ECMAScript functions.

Let me know if this sounds good to you and I will implement it.

**Comment by sradomski** [comment]
Introduced interpreter.serialize / deserialize and accompanying tests
