### ISSUE TITLE
Lua version for datamodel >= 5.2

### ISSUE THREAD

**Issue by EduardShaid** [tklab-tud/uscxml#95]
Dear Stefan !

Function call "lua_pcall ()" (in the module "Lua Data Model.cpp") has expired.
In Lua since version 5.2 of this function in lua library no more. Therefore, an error occurs when using datamodel.

Instead, use "lua_pcallk ()"

**Comment by EduardShaid** [comment]
here is an example:

```
ed@ubuntu:/usr/uscxml/build$ lua -i
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
> r = require("uscxmlNativeLua");
> scxml = r.Interpreter.fromURL("test199.scxml");
> state = r.USCXML_UNDEF;
> repeat state = scxml:step(); print(state); until state == r.USCXML_FINISHED 
2016-08-27 08:00:31,901 INFO  HTTPServer.cpp:568: Registering at unstarted HTTP Server
2016-08-27 08:00:31,902 INFO  LuaDataModel.cpp:207: error loading module 'lxp' from file '/usr/lib/lua/5.2/lxp.so':
	/usr/lib/lua/5.2/lxp.so: undefined symbol: lua_pcall
2
2016-08-27 08:00:31,902 ERROR BasicContentExecutor.cpp:361:     name: error.execution
    data: 
  {
    "cause": "Type '27' not supported for sending", 
    "xpath": "//state[@id=\"s0\"]/onentry[1]/send[1]"
  }


4
5
Outcome: "pass"
4
-1
```

**Comment by sradomski** [comment]
Awesome! I'll have a look at the 5.2 API as soon as I have some spare time.

**Comment by EduardShaid** [comment]
Dear Stefan !

Tell me how to work with HTTP-server and WebSocket-server ?
How to pass through these events ?
Give me an example of the real URL to access HTTP-server.

Thank you !

**Comment by EduardShaid** [comment]
Dear Stefan !

I figured all over, the project works fine. Of course, the fix will be in the project. But the project itself, I think, in the future will be a success in IoT.

Thank you !
