### ISSUE TITLE
How apply ActionLanguage to invokers?

### ISSUE THREAD

**Issue by alexzhornyak** [tklab-tud/uscxml#96]
Hello,
I created my custom DelayedEventQueue and passed it through the ActionLanguage class
```
AviaDelayedEventQueue *aviaqueue = new AviaDelayedEventQueue(g_intepreter.getImpl().get());
aviaqueue->getElapsed = std::bind(&Timer::getElapsed,&g_Timer);
ActionLanguage lang;
lang.delayedQueue = DelayedEventQueue(std::shared_ptr<DelayedEventQueueImpl>(aviaqueue));
g_intepreter.setActionLanguage(lang);
```

It works fine but affect only on top level interpreter. 
How override delayed event queue in invokers?

I tried to register custom invoker as written in the code below
```
namespace uscxml {

	class ScxmlDelayInvoker :
		public USCXMLInvoker
	{
		ActionLanguage *lang_;
	public:
		ScxmlDelayInvoker(ActionLanguage *ALang);
		virtual ~ScxmlDelayInvoker();

		std::shared_ptr<InvokerImpl> ScxmlDelayInvoker::create(InterpreterImpl* interpreter) {
		// variant 1
		/*AviaDelayedEventQueue *aviaqueue = new AviaDelayedEventQueue(interpreter);
		aviaqueue->getElapsed = std::bind(&Timer::getElapsed, _pTimer);
		
		ActionLanguage lang;
		lang.delayedQueue =
			DelayedEventQueue(std::shared_ptr<DelayedEventQueueImpl>(aviaqueue));*/
		
		// variant 2
		interpreter->setActionLanguage(*lang_);

		std::shared_ptr<ScxmlDelayInvoker> invoker(new ScxmlDelayInvoker(lang_));
		invoker->_interpreter = interpreter;

		return invoker;
	}

		virtual std::list<std::string> getNames() {
			std::list<std::string> names;
			names.push_back("delay_scxml");
			return names;
		}
	};

}

ScxmlDelayInvoker *delayinvoker = new ScxmlDelayInvoker(&lang);
Factory::getInstance()->registerInvoker(delayinvoker);
```

But during invoke I've got fatal error (AccessViolation) and I think that I'm not doing it correctly.
So, where is my mistake?

**Comment by sradomski** [comment]
I am not sure what you are trying to do with the `ScxmlDelayInvoker` but I can answer the question about the ActionLanguage instances only being valid for the topmost SCXML interpreter: that's a deficiency of the current API. Currently, there is no way to pass a custom ActionLanguage to the nested SCXML interpreters and I am open to suggestions as to how to implement it.

The usual approach to extend the interpreter is to register prototype instances of I/O processors, invokers and datamodels with the `Factory` and have the interpreter request new instances via their `create` methods when it is itself instantiated. The ActionLanguage circumvents this mechanism and extends it e.g. for the `DelayQueue` implementation and the `ContentExecutor` but is only available for the topmost interpreter as nested interpreters will not care for their parent's ActionLanguage. One approach may be to require a factory method ala `create` in the classes of the ActionLanguage and have the nested interpreters call these to get new instances. If this is acceptable, I can implement it.

The AccessViolation for your custom invoker seems like an unrelated issue and while I'd like to help you here, please post another issue with all the relevant files (*.cpp, *.scxml) that are required for me to reproduce the error.

**Comment by sradomski** [comment]
I did implement `create` Factory methods for all classes in the ActionLanguage which are called when an invoked SCXML interpreter is instantiated. Let me know if this solves your problem. With regard to the invoker, I am still not sure what you need - do provide the files to recreate in a new issue please.

**Comment by alexzhornyak** [comment]
I will so appreciated for you if you have an opportunity to look at my source code.
I will post it as link, because can not attach it using github. It all time writes that can not support that file type, though I've packed it into zip.

[Source code with issue](https://www.dropbox.com/s/6cos9cmkq9e31um/uscxml_tester_ex.zip?dl=0)

Ok, so the main idea of this source code is to change global time to my custom timer with an opportunity of pause/resume.

**Comment by alexzhornyak** [comment]
I have corrected my code according your latest recomendation.
Here is a link again
[source code](https://www.dropbox.com/s/c1wyx3dwt9j9xvg/uscxml_tester_ex2.zip?dl=0)

But now I have [this problem](https://github.com/tklab-tud/uscxml/issues/97)

**Comment by sradomski** [comment]
I implemented a [pauseable / resumable event queue](https://github.com/tklab-tud/uscxml/blob/master/test/src/test-extensions.cpp#L52) as I'd do it: Inherit `BasicDelayedEventQueue` to get the basic functionality right and provide the means to pause / resume it. The approach is platform independent and does not introduce any new dependencies, neither onto more libraries nor additional language features.

I am closing this issue. If there is still something left to be done here, please open a new issue with an appropriate title.
